name: 'Run EE server for another Docker container'
description: 'Run EE server and configure tests to connect to it from another Docker container'
inputs:
  # All inputs in composite actions are strings
  use-server-rc:
    required: true
    default: false
  server-tag:
    required: true
    default: 'latest'
  # Github Composite Actions can't access secrets
  # so we need to pass them in as inputs
  docker-hub-username:
    required: false
  docker-hub-password:
    required: false

runs:
  using: "composite"
  steps:
  - name: Run EE server
    uses: ./.github/actions/run-ee-server
    with:
      use-server-rc: ${{ inputs.use-server-rc }}
      server-tag: ${{ inputs.server-tag }}
      docker-hub-username: ${{ inputs.docker-hub-username }}
      docker-hub-password: ${{ inputs.docker-hub-password }}

  - name: Get IP address of Docker container hosting server
    id: get-server-ip-address
    run: echo server-ip=$(docker container inspect -f '{{ .NetworkSettings.IPAddress }}' aerospike) >> $GITHUB_OUTPUT
    shell: bash


  - name: Configure tests to connect to that Docker container
    run: |
      pipx install crudini --pip-args "-c ${{ github.workspace }}/.github/workflows/requirements.txt";
      crudini --existing=param --set config.conf enterprise-edition hosts ${{ steps.get-server-ip-address.outputs.server-ip }}:3000;
      cat config.conf
    working-directory: .github/workflows
    shell: bash
