name: 'Install Docker on macOS runner'
description: 'Install Docker using colima'

runs:
  using: "composite"
  steps:

  - name: Configure Homebrew cache
    uses: actions/cache@v4
    id: brew-cache
    with:
      path: |
        ~/Library/Caches/Homebrew/colima*
        ~/Library/Caches/Homebrew/coreutils*
        ~/Library/Caches/Homebrew/docker*
      key: brew-v1
      #restore-keys: brew-

  - name: Turn off update
    run: export HOMEBREW_NO_AUTO_UPDATE=1
    shell: bash

  - name: 'macOS: install timeout command'
    run: brew install coreutils -q --display-times
    shell: bash

  - name: Install Docker Engine
    run: brew install colima -q --display-times
    shell: bash

  - name: Install Docker client
    run: brew install docker -q --display-times
    shell: bash

  - name: Save cache
    if: steps.brew-cache.outputs.cache-hit == 'false'
    uses: actions/cache/save@v4
    with:
      path: ${{ inputs.path }}
      key: brew-v1

  - name: Start Docker Engine
    run: colima start
    shell: bash
