require:
  - choma
  - mocha-clean
spec:
  - "test/*.js" # the positional arguments!
  - "test/*.mts" # the positional arguments!
node-option:
  - "import=tsx"
parallel: false
inline-diffs: true
color: true
