name: 'Run EE Server'
description: 'Run EE server'
inputs:
  # All inputs in composite actions are strings
  use-server-rc:
    required: true
    default: false
  server-tag:
    required: true
    default: 'latest'
  # Github Composite Actions can't access secrets
  # so we need to pass them in as inputs
  docker-hub-username:
    required: false
  docker-hub-password:
    required: false

runs:
  using: "composite"
  steps:
  - name: Create config folder to store configs in
    run: mkdir configs
    shell: bash

  - name: Use release server
    if: ${{ inputs.use-server-rc == 'false' }}
    run: echo "SERVER_IMAGE=aerospike/aerospike-server-enterprise" >> $GITHUB_ENV
    shell: bash

  - name: Use release candidate server
    if: ${{ inputs.use-server-rc == 'true' }}
    run: echo "SERVER_IMAGE=aerospike/aerospike-server-enterprise-rc" >> $GITHUB_ENV
    shell: bash

  - name: Log into Docker Hub to get server RC
    if: ${{ inputs.use-server-rc == 'true' }}
    run: docker login --username ${{ inputs.docker-hub-username }} --password ${{ inputs.docker-hub-password }}
    shell: bash

  - name: Get default aerospike.conf from Docker server EE container
    run: |
      docker run -d --name aerospike -p 3000-3002:3000-3002 $SERVER_IMAGE:${{ inputs.server-tag }}
      sleep 5
      docker cp aerospike:/etc/aerospike/aerospike.conf ./configs/aerospike.conf
      docker container stop aerospike
      docker container rm aerospike
    shell: bash

  - name: Enable security features using aerospike.conf
    # Security stanza
    run: echo -e "security {\n\tenable-quotas true\n}\n" >> ./aerospike.conf
    working-directory: ./configs
    shell: bash

  - name: Run enterprise edition server
    run: docker run -tid -v $(pwd)/configs:/opt/aerospike/etc -p 3000:3000 --name aerospike $SERVER_IMAGE:${{ inputs.server-tag }} asd --config-file /opt/aerospike/etc/aerospike.conf
    shell: bash

  - name: Create user in database for tests
    # Use default admin user to create another user for testing
    run: docker exec aerospike asadm --user admin --password admin --enable -e "manage acl create user superuser password superuser roles read-write-udf sys-admin user-admin data-admin"
    shell: bash