// *****************************************************************************
// Copyright 2013-2026 Aerospike, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// *****************************************************************************

'use strict'

const as = require('bindings')('aerospike.node')

/**
 * @module aerospike/subcode
 *
 * @description Server error detail verbosity levels and subcode constants.
 *
 * Subcodes are organized by parent status code. A subcode integer is only
 * meaningful paired with its parent {@link module:aerospike/status|status code}.
 * Always dispatch on the `(code, subcode)` pair.
 */

/**
 * No error details requested (default).
 * @const {number}
 */
exports.ERROR_DETAIL_NONE = exports.AEROSPIKE_ERROR_DETAIL_NONE =
  as.subcode.AEROSPIKE_ERROR_DETAIL_NONE

/**
 * Request subcode only from the server on error responses.
 * @const {number}
 */
exports.ERROR_DETAIL_SUBCODE = exports.AEROSPIKE_ERROR_DETAIL_SUBCODE =
  as.subcode.AEROSPIKE_ERROR_DETAIL_SUBCODE

/**
 * Request subcode and human-readable message from the server on error responses.
 * @const {number}
 */
exports.ERROR_DETAIL_MESSAGE = exports.AEROSPIKE_ERROR_DETAIL_MESSAGE =
  as.subcode.AEROSPIKE_ERROR_DETAIL_MESSAGE

/**
 * No subcode returned. Reserved as 0 across all status families.
 * @const {number}
 */
exports.NONE = exports.AEROSPIKE_SUB_NONE = as.subcode.AEROSPIKE_SUB_NONE

exports.PARAM_TTL_INVALID = exports.AEROSPIKE_SUB_PARAM_TTL_INVALID =
  as.subcode.AEROSPIKE_SUB_PARAM_TTL_INVALID

exports.PARAM_BITS_OFFSET_OUT_OF_RANGE =
  exports.AEROSPIKE_SUB_PARAM_BITS_OFFSET_OUT_OF_RANGE =
    as.subcode.AEROSPIKE_SUB_PARAM_BITS_OFFSET_OUT_OF_RANGE

exports.PARAM_BITS_SIZE_OUT_OF_RANGE =
  exports.AEROSPIKE_SUB_PARAM_BITS_SIZE_OUT_OF_RANGE =
    as.subcode.AEROSPIKE_SUB_PARAM_BITS_SIZE_OUT_OF_RANGE

exports.PARAM_BITS_RESIZE_EXCEEDED = exports.AEROSPIKE_SUB_PARAM_BITS_RESIZE_EXCEEDED =
  as.subcode.AEROSPIKE_SUB_PARAM_BITS_RESIZE_EXCEEDED

exports.PARAM_BIN_COUNT_TOO_LARGE = exports.AEROSPIKE_SUB_PARAM_BIN_COUNT_TOO_LARGE =
  as.subcode.AEROSPIKE_SUB_PARAM_BIN_COUNT_TOO_LARGE

exports.UNAVAIL_INITIAL_BALANCE_UNRESOLVED =
  exports.AEROSPIKE_SUB_UNAVAIL_INITIAL_BALANCE_UNRESOLVED =
    as.subcode.AEROSPIKE_SUB_UNAVAIL_INITIAL_BALANCE_UNRESOLVED

exports.UNAVAIL_REPLICA_UNAVAILABLE = exports.AEROSPIKE_SUB_UNAVAIL_REPLICA_UNAVAILABLE =
  as.subcode.AEROSPIKE_SUB_UNAVAIL_REPLICA_UNAVAILABLE

exports.UNSUPP_FEAT_MRT_REQUIRES_STRONG_CONSISTENCY =
  exports.AEROSPIKE_SUB_UNSUPP_FEAT_MRT_REQUIRES_STRONG_CONSISTENCY =
    as.subcode.AEROSPIKE_SUB_UNSUPP_FEAT_MRT_REQUIRES_STRONG_CONSISTENCY

exports.UNSUPP_FEAT_GENERIC = exports.AEROSPIKE_SUB_UNSUPP_FEAT_GENERIC =
  as.subcode.AEROSPIKE_SUB_UNSUPP_FEAT_GENERIC

exports.BIN_NOT_FOUND_HLL_CANNOT_CREATE_WITH_OP =
  exports.AEROSPIKE_SUB_BIN_NOT_FOUND_HLL_CANNOT_CREATE_WITH_OP =
    as.subcode.AEROSPIKE_SUB_BIN_NOT_FOUND_HLL_CANNOT_CREATE_WITH_OP

exports.BIN_NAME_COUNT_TOO_LARGE = exports.AEROSPIKE_SUB_BIN_NAME_COUNT_TOO_LARGE =
  as.subcode.AEROSPIKE_SUB_BIN_NAME_COUNT_TOO_LARGE

exports.FORBID_XDR_FILTER_BLOCKED = exports.AEROSPIKE_SUB_FORBID_XDR_FILTER_BLOCKED =
  as.subcode.AEROSPIKE_SUB_FORBID_XDR_FILTER_BLOCKED

exports.FORBID_SET_COUNT_STOP_WRITES =
  exports.AEROSPIKE_SUB_FORBID_SET_COUNT_STOP_WRITES =
    as.subcode.AEROSPIKE_SUB_FORBID_SET_COUNT_STOP_WRITES

exports.FORBID_SET_SIZE_STOP_WRITES = exports.AEROSPIKE_SUB_FORBID_SET_SIZE_STOP_WRITES =
  as.subcode.AEROSPIKE_SUB_FORBID_SET_SIZE_STOP_WRITES

exports.FORBID_CLOCK_SKEW_STOP_WRITES =
  exports.AEROSPIKE_SUB_FORBID_CLOCK_SKEW_STOP_WRITES =
    as.subcode.AEROSPIKE_SUB_FORBID_CLOCK_SKEW_STOP_WRITES

exports.FORBID_REPLACE_CONFLICT_RESOLVING =
  exports.AEROSPIKE_SUB_FORBID_REPLACE_CONFLICT_RESOLVING =
    as.subcode.AEROSPIKE_SUB_FORBID_REPLACE_CONFLICT_RESOLVING

exports.FORBID_TRUNCATED = exports.AEROSPIKE_SUB_FORBID_TRUNCATED =
  as.subcode.AEROSPIKE_SUB_FORBID_TRUNCATED

exports.FORBID_MASKING_POLICY_BLOCKED =
  exports.AEROSPIKE_SUB_FORBID_MASKING_POLICY_BLOCKED =
    as.subcode.AEROSPIKE_SUB_FORBID_MASKING_POLICY_BLOCKED

exports.FORBID_DURABILITY_VIOLATION = exports.AEROSPIKE_SUB_FORBID_DURABILITY_VIOLATION =
  as.subcode.AEROSPIKE_SUB_FORBID_DURABILITY_VIOLATION

exports.FORBID_MASKING_ROLE_VIOLATION =
  exports.AEROSPIKE_SUB_FORBID_MASKING_ROLE_VIOLATION =
    as.subcode.AEROSPIKE_SUB_FORBID_MASKING_ROLE_VIOLATION

exports.OPNOT_CDT_INDEX_OUT_OF_BOUNDS =
  exports.AEROSPIKE_SUB_OPNOT_CDT_INDEX_OUT_OF_BOUNDS =
    as.subcode.AEROSPIKE_SUB_OPNOT_CDT_INDEX_OUT_OF_BOUNDS

exports.OPNOT_CDT_RANK_OUT_OF_BOUNDS =
  exports.AEROSPIKE_SUB_OPNOT_CDT_RANK_OUT_OF_BOUNDS =
    as.subcode.AEROSPIKE_SUB_OPNOT_CDT_RANK_OUT_OF_BOUNDS

exports.OPNOT_CDT_BOUNDED_LIST_OVERFLOW =
  exports.AEROSPIKE_SUB_OPNOT_CDT_BOUNDED_LIST_OVERFLOW =
    as.subcode.AEROSPIKE_SUB_OPNOT_CDT_BOUNDED_LIST_OVERFLOW

exports.OPNOT_HLL_INDEX_BITS_UNSET = exports.AEROSPIKE_SUB_OPNOT_HLL_INDEX_BITS_UNSET =
  as.subcode.AEROSPIKE_SUB_OPNOT_HLL_INDEX_BITS_UNSET

exports.OPNOT_HLL_CANNOT_REDUCE_INDEX_BITS =
  exports.AEROSPIKE_SUB_OPNOT_HLL_CANNOT_REDUCE_INDEX_BITS =
    as.subcode.AEROSPIKE_SUB_OPNOT_HLL_CANNOT_REDUCE_INDEX_BITS

exports.OPNOT_HLL_CANNOT_REDUCE_MINHASH_BITS =
  exports.AEROSPIKE_SUB_OPNOT_HLL_CANNOT_REDUCE_MINHASH_BITS =
    as.subcode.AEROSPIKE_SUB_OPNOT_HLL_CANNOT_REDUCE_MINHASH_BITS

exports.OPNOT_HLL_CANNOT_FOLD_MINHASH = exports.AEROSPIKE_SUB_OPNOT_HLL_CANNOT_FOLD_MINHASH =
  as.subcode.AEROSPIKE_SUB_OPNOT_HLL_CANNOT_FOLD_MINHASH

exports.OPNOT_HLL_FOLD_INDEX_BITS_TOO_LARGE =
  exports.AEROSPIKE_SUB_OPNOT_HLL_FOLD_INDEX_BITS_TOO_LARGE =
    as.subcode.AEROSPIKE_SUB_OPNOT_HLL_FOLD_INDEX_BITS_TOO_LARGE

exports.OPNOT_HLL_INTERSECT_MINHASH_MISMATCH =
  exports.AEROSPIKE_SUB_OPNOT_HLL_INTERSECT_MINHASH_MISMATCH =
    as.subcode.AEROSPIKE_SUB_OPNOT_HLL_INTERSECT_MINHASH_MISMATCH

exports.FILTERED_META = exports.AEROSPIKE_SUB_FILTERED_META =
  as.subcode.AEROSPIKE_SUB_FILTERED_META

exports.FILTERED_BINS = exports.AEROSPIKE_SUB_FILTERED_BINS =
  as.subcode.AEROSPIKE_SUB_FILTERED_BINS

exports.FILTERED_META_EVAL_FAILED = exports.AEROSPIKE_SUB_FILTERED_META_EVAL_FAILED =
  as.subcode.AEROSPIKE_SUB_FILTERED_META_EVAL_FAILED

exports.FILTERED_BINS_EVAL_FAILED = exports.AEROSPIKE_SUB_FILTERED_BINS_EVAL_FAILED =
  as.subcode.AEROSPIKE_SUB_FILTERED_BINS_EVAL_FAILED

exports.MRT_BLOCKED_RECORD_LOCKED = exports.AEROSPIKE_SUB_MRT_BLOCKED_RECORD_LOCKED =
  as.subcode.AEROSPIKE_SUB_MRT_BLOCKED_RECORD_LOCKED

exports.MRT_BLOCKED_ID_MISMATCH = exports.AEROSPIKE_SUB_MRT_BLOCKED_ID_MISMATCH =
  as.subcode.AEROSPIKE_SUB_MRT_BLOCKED_ID_MISMATCH
