/*******************************************************************************
 * Copyright 2013-2026 Aerospike, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <nan.h>
#include <node.h>

extern "C" {
#include <aerospike/as_subcode.h>
}

using namespace v8;

#define set(__obj, __name, __value)                                            \
	Nan::Set(__obj, Nan::New(__name).ToLocalChecked(), Nan::New(__value))

Local<Object> subcode()
{
	Nan::EscapableHandleScope scope;
	Local<Object> obj = Nan::New<Object>();

	set(obj, "AEROSPIKE_ERROR_DETAIL_NONE", AS_ERROR_DETAIL_NONE);
	set(obj, "AEROSPIKE_ERROR_DETAIL_SUBCODE", AS_ERROR_DETAIL_SUBCODE);
	set(obj, "AEROSPIKE_ERROR_DETAIL_MESSAGE", AS_ERROR_DETAIL_MESSAGE);
	set(obj, "AEROSPIKE_ERROR_DETAIL_EXP_TRACE", AS_ERROR_DETAIL_EXP_TRACE);

	set(obj, "AEROSPIKE_SUB_NONE", AS_SUB_NONE);

	set(obj, "AEROSPIKE_SUB_PARAM_TTL_INVALID", AS_SUB_PARAM_TTL_INVALID);
	set(obj, "AEROSPIKE_SUB_PARAM_BITS_OFFSET_OUT_OF_RANGE",
		AS_SUB_PARAM_BITS_OFFSET_OUT_OF_RANGE);
	set(obj, "AEROSPIKE_SUB_PARAM_BITS_SIZE_OUT_OF_RANGE",
		AS_SUB_PARAM_BITS_SIZE_OUT_OF_RANGE);
	set(obj, "AEROSPIKE_SUB_PARAM_BITS_RESIZE_EXCEEDED",
		AS_SUB_PARAM_BITS_RESIZE_EXCEEDED);
	set(obj, "AEROSPIKE_SUB_PARAM_BIN_COUNT_TOO_LARGE",
		AS_SUB_PARAM_BIN_COUNT_TOO_LARGE);
	set(obj, "AEROSPIKE_SUB_PARAM_STRING_CTX_MALFORMED",
		AS_SUB_PARAM_STRING_CTX_MALFORMED);

	set(obj, "AEROSPIKE_SUB_UNAVAIL_INITIAL_BALANCE_UNRESOLVED",
		AS_SUB_UNAVAIL_INITIAL_BALANCE_UNRESOLVED);
	set(obj, "AEROSPIKE_SUB_UNAVAIL_REPLICA_UNAVAILABLE",
		AS_SUB_UNAVAIL_REPLICA_UNAVAILABLE);

	set(obj, "AEROSPIKE_SUB_UNSUPP_FEAT_MRT_REQUIRES_STRONG_CONSISTENCY",
		AS_SUB_UNSUPP_FEAT_MRT_REQUIRES_STRONG_CONSISTENCY);
	set(obj, "AEROSPIKE_SUB_UNSUPP_FEAT_GENERIC", AS_SUB_UNSUPP_FEAT_GENERIC);

	set(obj, "AEROSPIKE_SUB_BIN_NOT_FOUND_HLL_CANNOT_CREATE_WITH_OP",
		AS_SUB_BIN_NOT_FOUND_HLL_CANNOT_CREATE_WITH_OP);

	set(obj, "AEROSPIKE_SUB_BIN_NAME_COUNT_TOO_LARGE",
		AS_SUB_BIN_NAME_COUNT_TOO_LARGE);

	set(obj, "AEROSPIKE_SUB_FORBID_XDR_FILTER_BLOCKED",
		AS_SUB_FORBID_XDR_FILTER_BLOCKED);
	set(obj, "AEROSPIKE_SUB_FORBID_SET_COUNT_STOP_WRITES",
		AS_SUB_FORBID_SET_COUNT_STOP_WRITES);
	set(obj, "AEROSPIKE_SUB_FORBID_SET_SIZE_STOP_WRITES",
		AS_SUB_FORBID_SET_SIZE_STOP_WRITES);
	set(obj, "AEROSPIKE_SUB_FORBID_CLOCK_SKEW_STOP_WRITES",
		AS_SUB_FORBID_CLOCK_SKEW_STOP_WRITES);
	set(obj, "AEROSPIKE_SUB_FORBID_REPLACE_CONFLICT_RESOLVING",
		AS_SUB_FORBID_REPLACE_CONFLICT_RESOLVING);
	set(obj, "AEROSPIKE_SUB_FORBID_TRUNCATED", AS_SUB_FORBID_TRUNCATED);
	set(obj, "AEROSPIKE_SUB_FORBID_MASKING_POLICY_BLOCKED",
		AS_SUB_FORBID_MASKING_POLICY_BLOCKED);
	set(obj, "AEROSPIKE_SUB_FORBID_DURABILITY_VIOLATION",
		AS_SUB_FORBID_DURABILITY_VIOLATION);
	set(obj, "AEROSPIKE_SUB_FORBID_MASKING_ROLE_VIOLATION",
		AS_SUB_FORBID_MASKING_ROLE_VIOLATION);

	set(obj, "AEROSPIKE_SUB_OPNOT_CDT_INDEX_OUT_OF_BOUNDS",
		AS_SUB_OPNOT_CDT_INDEX_OUT_OF_BOUNDS);
	set(obj, "AEROSPIKE_SUB_OPNOT_CDT_RANK_OUT_OF_BOUNDS",
		AS_SUB_OPNOT_CDT_RANK_OUT_OF_BOUNDS);
	set(obj, "AEROSPIKE_SUB_OPNOT_CDT_BOUNDED_LIST_OVERFLOW",
		AS_SUB_OPNOT_CDT_BOUNDED_LIST_OVERFLOW);
	set(obj, "AEROSPIKE_SUB_OPNOT_HLL_INDEX_BITS_UNSET",
		AS_SUB_OPNOT_HLL_INDEX_BITS_UNSET);
	set(obj, "AEROSPIKE_SUB_OPNOT_HLL_CANNOT_REDUCE_INDEX_BITS",
		AS_SUB_OPNOT_HLL_CANNOT_REDUCE_INDEX_BITS);
	set(obj, "AEROSPIKE_SUB_OPNOT_HLL_CANNOT_REDUCE_MINHASH_BITS",
		AS_SUB_OPNOT_HLL_CANNOT_REDUCE_MINHASH_BITS);
	set(obj, "AEROSPIKE_SUB_OPNOT_HLL_CANNOT_FOLD_MINHASH",
		AS_SUB_OPNOT_HLL_CANNOT_FOLD_MINHASH);
	set(obj, "AEROSPIKE_SUB_OPNOT_HLL_FOLD_INDEX_BITS_TOO_LARGE",
		AS_SUB_OPNOT_HLL_FOLD_INDEX_BITS_TOO_LARGE);
	set(obj, "AEROSPIKE_SUB_OPNOT_HLL_INTERSECT_MINHASH_MISMATCH",
		AS_SUB_OPNOT_HLL_INTERSECT_MINHASH_MISMATCH);
	set(obj, "AEROSPIKE_SUB_OPNOT_STRING_CONVERSION_FAILED",
		AS_SUB_OPNOT_STRING_CONVERSION_FAILED);
	set(obj, "AEROSPIKE_SUB_OPNOT_STRING_UTF8_INVALID",
		AS_SUB_OPNOT_STRING_UTF8_INVALID);
	set(obj, "AEROSPIKE_SUB_OPNOT_STRING_REGEX_LIMIT_EXCEEDED",
		AS_SUB_OPNOT_STRING_REGEX_LIMIT_EXCEEDED);
	set(obj, "AEROSPIKE_SUB_OPNOT_STRING_B64_INVALID",
		AS_SUB_OPNOT_STRING_B64_INVALID);

	set(obj, "AEROSPIKE_SUB_FILTERED_META", AS_SUB_FILTERED_META);
	set(obj, "AEROSPIKE_SUB_FILTERED_BINS", AS_SUB_FILTERED_BINS);
	set(obj, "AEROSPIKE_SUB_FILTERED_META_EVAL_FAILED",
		AS_SUB_FILTERED_META_EVAL_FAILED);
	set(obj, "AEROSPIKE_SUB_FILTERED_BINS_EVAL_FAILED",
		AS_SUB_FILTERED_BINS_EVAL_FAILED);

	set(obj, "AEROSPIKE_SUB_MRT_BLOCKED_RECORD_LOCKED",
		AS_SUB_MRT_BLOCKED_RECORD_LOCKED);
	set(obj, "AEROSPIKE_SUB_MRT_BLOCKED_ID_MISMATCH",
		AS_SUB_MRT_BLOCKED_ID_MISMATCH);

	return scope.Escape(obj);
}
