#!/bin/sh
# Runs tests cases in a randomized order to help detect interdependencies between tests.
# npm test is setup to run the tests via this script.
# To re-run test cases in the same order as during some previous iteration,
# capture the random seed that's printed at the beginning and end of the test
# run and set the RANDOM_SEED environment variable to that value before
# rerunning this script, e.g.
#
#   $ RANDOM_SEED=48038 npm test
#   Running tests in randomized order. Use RANDOM_SEED=48038 to reproduce.
#   ....
#
RANDOM_SEED=${RANDOM_SEED:-$RANDOM}
shuffle () {
  awk -v Seed=$RANDOM_SEED 'BEGIN { if (Seed) { srand(Seed) } else { srand() }; OFMT="%.17f"} {print rand(), $0}' "$@" | sort -k1,1n | cut -d ' ' -f2-
}
echo "Running tests in randomized order. Use RANDOM_SEED=${RANDOM_SEED} to reproduce."
tests=`ls test/*.js | shuffle`
mocha $tests
success=$?
echo "Tests executed in randomized order. Use RANDOM_SEED=${RANDOM_SEED} to reproduce."
exit $success
