name: 'Wait for Aerospike server to start'
description: Only tested on Linux and macOS
inputs:
  container-name:
    required: true
  is-security-enabled:
    required: false
    default: 'false'
  is-strong-consistency-enabled:
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
  - name: 'macOS: install timeout command'
    if: ${{ runner.os == 'macOS' }}
    run: brew install coreutils
    shell: bash

  # Composite actions doesn't support step-level timeout-minutes
  # Use timeout command and store polling logic in file to make it easier to read
  # Call bash shell explicitly since timeout uses "sh" shell by default, for some reason
  # Also, we don't want to fail if we timeout in case the server *did* finish starting up but the script couldn't detect it due to a bug
  # Effectively, this composite action is like calling "sleep" that is optimized to exit early when it detects an ok from the server
  - name: Wait for EE server to start
    run: timeout 30 bash ./.github/workflows/wait-for-as-server-to-start.bash ${{ inputs.container-name }} ${{ inputs.is-security-enabled }} ${{ inputs.is-strong-consistency-enabled }} || true
    shell: bash
