name: Dev workflow

# 1. When a PR review is requested, run tests on that PR
# 2. If all of the tests pass, allow the PR to be merged into `dev`
# 3. Whenever a PR is merged to `dev`, bump version number in `dev`

on:
  workflow_dispatch:
    # inputs:
    #   run_server_release_tests:
    #     description: 'DEBUG: Run server release tests in build-wheels workflow?'
    #     type: boolean
    #     default: false

jobs:
  bump-dev-number-and-tag:
    uses: ./.github/workflows/dev-bump-version.yml

  build-node-cpp-addons:
    uses: ./.github/workflows/dev-build-node-cpp-addons.yml
    needs: [
      bump-dev-number-and-tag
    ]
    with:
      version: ${{ needs.bump-dev-number-and-tag.outputs.dev_version }}
      run_tests: false
    secrets:
      soup_hat: ${{ secrets.soup_hat }}
      cell_girl: ${{ secrets.cell_girl }}
      song_loss: ${{ secrets.song_loss }}

  # TODO: for now, use our own workflow because the shared-workflow's deploy workflow doesn't support npm repos
  upload-artifacts-as-jfrog-build:
    needs: [
      bump-dev-number-and-tag,
      build-node-cpp-addons
    ]
    runs-on: ubuntu-22.04
    permissions:
      # This is required for requesting the OIDC token
      id-token: write
      contents: read
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
        JF_PROJECT: database
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        pattern: '*.build'
        merge-multiple: true
        path: artifacts

    - run: |
        jf npm-config --repo-deploy=database-npm-dev-local
        ls -l artifacts/*.tgz | xargs -I -n1 jf npm publish --build-name=nodejs-client --build-number=${{ needs.bump-dev-number-and-tag.outputs.dev_version }} {}

  create-release-bundle:
    name: Create release bundle from JFrog build
    needs: [
      bump-dev-number-and-tag,
      upload-artifacts-as-jfrog-build
    ]
    uses: aerospike/shared-workflows/.github/workflows/reusable_create-release-bundle.yaml@8f53b63b33d86e63aeb37d951283dd974574885b
    with:
      jf-project: database
      jf-build-names: "nodejs-client"
      jf-bundle-name: "aerospike-nodejs-client"
      version: ${{ needs.bump-dev-number-and-tag.outputs.dev_version }}
      gh-workflows-ref: 8f53b63b33d86e63aeb37d951283dd974574885b
      dry-run: false
      oidc-provider-name: database-gh-aerospike
      oidc-audience: database-gh-aerospike
