name: Upload to JFrog

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_call:
    inputs:
      new_version:
        type: string
        required: false
      jfrog-repo-name:
        type: string
        required: false
        default: ${{ vars.JFROG_REPO_NAME }}

jobs:
  upload-to-jfrog:
    name: Upload artifacts to JFrog
    env:
      JFROG_RELEASE_BUNDLE_NAME: aerospike-nodejs-client
    runs-on: ubuntu-22.04
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
        
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Download from JFrog
      run: jf rt download "clients-npm-dev-local/aerospike/${{ env.VERSION }}/*"
      env:
        VERSION:  ${{ inputs.new_version }}

    - name: Move bindings to lib/binding
      run: |
        mkdir lib/binding;
        cp -r aerospike/${{ env.VERSION }}/* lib/binding;
        rm -rf aerospike;
      env:
        VERSION: ${{ inputs.new_version }} 

    - name: Update version in package.json
      run: 
        jq --arg v "${{ env.VERSION }}" '.version = $v' package.json > tmp.json && mv tmp.json package.json;
      env:
        VERSION: ${{ inputs.new_version }} 

    - name: Install dependencies and test install
      run:
        npm ci --ignore-scripts;

    - name: Create package tarball
      run: 
        npm pack;

    - name: Upload tarball to JFrog Nodejs repo
      run: jf rt upload --project clients --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "aerospike-${{ env.NEW_VERSION }}.tgz" clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/
      env:
        NEW_VERSION: ${{ inputs.new_version }}

    - name: Publish build info to JFrog Nodejs repo
      run: jf rt build-publish --project clients nodejs-client ${{ inputs.new_version }}

    - name: install moreutils
      run: sudo apt install -y moreutils

    # .files.project is not documented in JFrog but it's used to specify the JFrog project to upload this release bundle to
    - name: Create file spec for release bundle
      run: cat releasebundle-filespec.json | jq '.files[0].build = "nodejs-client/${{ inputs.new_version }}"' | sponge releasebundle-filespec.json
      working-directory: .github/workflows
      shell: bash

    - name: Create release bundle from JFrog build
      # Not the same name as in proxy/pom.xml
      # But that name doesn't specify the language,
      # and there can be multiple languages that implement the proxy client in the future that need to be uploaded to JFrog
      # Signing key only signs release bundle and not the artifacts associated with it
      run: jf release-bundle-create --project clients --signing-key=aerospike --sync --spec=./releasebundle-filespec.json ${{ env.JFROG_RELEASE_BUNDLE_NAME }} ${{ inputs.new_version }}
      working-directory: .github/workflows

    - name: Promote release bundle to DEV stage
      run: jf release-bundle-promote --project clients --signing-key=aerospike --sync ${{ env.JFROG_RELEASE_BUNDLE_NAME }} ${{ inputs.new_version }} DEV
      working-directory: .github/workflows