name: Publish JFrog build to NPM

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      old_version:
        type: string
        required: false
      new_version:
        type: string
        required: false
    secrets:
      # Just make all the secrets required to make things simpler...
      NPMRC:
        required: true
      NPMRC_OFF:
        required: true
      NPM_TOKEN_OFF:
        required: true


jobs:
  test-install-script:
    runs-on: ubuntu-22.04
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit
        
    - name: Set up JFrog credentials
      uses: jfrog/setup-jfrog-cli@5b06f730cc5a6f55d78b30753f8583454b08c0aa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}
        registry-url: 'https://registry.npmjs.org'

    - name: Download Artifacts from Jfrog
      run: jf rt dl "clients-npm-stage-local/aerospike/${{ env.OLD_VERSION }}/" "downloaded-artifacts/"
      env:
        OLD_VERSION: ${{ inputs.old_version }}
        PACKAGE_MANAGER: npm

    - name: Test install script for npm
      run: |
        tar --strip-components=1 -xvf aerospike-${{ env.OLD_VERSION }}.tgz;
        npm ci --ignore-scripts;
        npm-run-all removeExtraBinaries build;
        check-install-script-results.js;
      env:
        OLD_VERSION: ${{ inputs.old_version }}
      working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}
