name: Dev workflow

# 1. When a PR review is requested, run tests on that PR
# 2. If all of the tests pass, allow the PR to be merged into `dev`
# 3. Whenever a PR is merged to `dev`, bump version number in `dev`

on:
  workflow_dispatch:
    # inputs:
    #   run_server_release_tests:
    #     description: 'DEBUG: Run server release tests in build-wheels workflow?'
    #     type: boolean
    #     default: false

jobs:
  bump-dev-number-and-tag:
    uses: ./.github/workflows/dev-bump-version.yml

  build-node-cpp-addons:
    uses: ./.github/workflows/dev-build-node-cpp-addons.yml
    needs: [
      bump-dev-number-and-tag
    ]
    with:
      run_tests: false
    secrets:
      soup_hat: ${{ secrets.soup_hat }}
      cell_girl: ${{ secrets.cell_girl }}
      song_loss: ${{ secrets.song_loss }}

  create-release-bundle:
    name: Create release bundle from JFrog build
    needs: [
      bump-dev-number-and-tag,
      build-node-cpp-addons
    ]
    uses: ./.github/workflows/create-release-bundle.yml
    with:
      new_version: ${{ needs.bump-dev-number-and-tag.outputs.dev_version }}
