  # Takes in how to bump version as input
  # Commits changes to bump version and outputs the new version and commit hash as output
  name: Bump version

  permissions:
    # This is required for requesting the OIDC token
    id-token: write
    contents: read

  on:
    workflow_call:
      outputs:
        dev_version:
          value: ${{ jobs.get-new-version.outputs.dev_version }}

  jobs:

    get-new-version:
      name: Get new version string
      runs-on: ubuntu-22.04
      outputs:
        dev_version: ${{ steps.get-new-version.outputs.dev_version }}
      steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up JFrog credentials
        uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
        env:
          JF_URL: https://aerospike.jfrog.io
        with:
          oidc-provider-name: gh-aerospike-clients
          oidc-audience: aerospike/clients

      - name: Get version from JFROG repository
        id: get-jfrog-version
        run: |
          echo "jfrog_version=$(jfrog rt s "clients-npm-dev-local/aerospike/*" | jq -r '.[]?.path | capture("aerospike/(?<version>[^/]+)") | .version' | grep -v '^-$' | grep -v '^lib$' | sort -V | grep -v 'rc' | tail -n1)" >> $GITHUB_OUTPUT

      - name: Get version from github repository
        id: get-github-version
        run: |
          echo "github_version=$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT

      - name: Print versions
        run: |
          echo "jfrog version is ${{ steps.get-jfrog-version.outputs.jfrog_version }}"
          echo "github version is ${{ steps.get-github-version.outputs.github_version }}"

      - name: Install library that parses nodejs versions
        run: npm install semver@7.7.2 --ignore-scripts
        working-directory: .github/workflows

      - name: Get new version
        id: get-new-version
        run: |
          set -e;
          dev_version=$(node dev-bump-version.js ${{ steps.get-github-version.outputs.github_version }} ${{ steps.get-jfrog-version.outputs.jfrog_version }});
          echo "dev_version=$dev_version" >> $GITHUB_OUTPUT;
        working-directory: .github/workflows

      - name: Print new version
        run: |
          echo "${{ steps.get-new-version.outputs.dev_version }}"
