name: Build Node C++ Addons
run-name: Build Node C++ Addons (run_tests=${{ inputs.run_tests }}, publish-build-info=${{ inputs.publish-build-info }})

on:
  workflow_dispatch:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: false
      publish-build-info:
        required: false
        type: boolean
        default: false
      version:
        type: string
        required: false
      server-tag:
        type: string
        required: false
        default: 'latest'
  workflow_call:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: false
      publish-build-info:
        required: false
        type: boolean
        default: false
      version:
        type: string
        required: true
      jf-build-id:
        type: string
        required: false
        default: ''
      is_workflow_call:
        type: boolean
        default: true
        required: false
      server-tag:
        type: string
        required: false
        default: 'latest'
    secrets:
      soup_hat:
        required: true
      cell_girl:
        required: true
      song_loss:
        required: true

jobs:
  build-node-cpp-bindings:
    strategy:
      matrix:
        platform-tag: [
          "manylinux_x86_64",
          "manylinux_aarch64",
          "macosx_x86_64",
          "macosx_x86_64_2",
          "macosx_arm64",
          "macosx_arm64_2",
          "win_amd64"
        ]
      fail-fast: false
    uses: ./.github/workflows/dev-build-node-cpp-bindings.yml
    with:
      platform-tag: ${{ matrix.platform-tag }}
      run_tests: ${{ inputs.run_tests }}
      publish-build-info: ${{ inputs.publish-build-info }}
      jf-build-id: ${{ inputs.jf-build-id }}
      use-server-rc: false
      server-tag: ${{ inputs.server-tag }}
      version: ${{ inputs.version }}
    secrets:
      soup_hat: ${{ secrets.soup_hat }}
      cell_girl: ${{ secrets.cell_girl }}
      song_loss: ${{ secrets.song_loss }}
