name: Dev workflow

# 1. When a PR review is requested, run tests on that PR
# 2. If all of the tests pass, allow the PR to be merged into `dev`
# 3. Whenever a PR is merged to `dev`, bump version number in `dev`

on:
  push:
    branches:
      - 'CLIENT*'

  # So we can test changes to the test-server-rc workflow
  workflow_dispatch:
    inputs:
      run_server_release_tests:
        description: 'DEBUG: Run server release tests in build-wheels workflow?'
        type: boolean
        default: false

jobs:
  bump-dev-number:
    uses: ./.github/workflows/dev-bump-version.yml

  build-node-cpp-addons:
    uses: ./.github/workflows/dev-build-node-cpp-addons.yml
    needs: [
      bump-dev-number
    ]
    with:
      version: ${{ needs.bump-dev-number.outputs.dev_version }}
      run_tests: false
    secrets:
      soup_hat: ${{ secrets.soup_hat }}
      cell_girl: ${{ secrets.cell_girl }}
      song_loss: ${{ secrets.song_loss }}

  upload-addons-to-jfrog:
    name: Upload artifacts to JFrog
    needs: [
      bump-dev-number,
      build-node-cpp-addons
    ]
    uses: ./.github/workflows/dev-upload-addons-to-jfrog.yml
    with:
      new_version: ${{ needs.bump-dev-number.outputs.dev_version }}

  # upload-npm-package-to-jfrog:
  #   name: upload package to JFrog NPM
  #   needs: [
  #     bump-dev-number,
  #     build-node-cpp-addons,
  #     upload-addons-to-jfrog,
  #   ]
  #   uses: ./.github/workflows/shared-upload-npm-package-to-jfrog.yml
  #   with:
  #     new_version: ${{ needs.bump-dev-number.outputs.dev_version }}
  #     pipeline-stage: 'dev'
  #   secrets:
  #     plane_grass: ${{ secrets.plane_grass }}
