  # Takes in how to bump version as input
  # Commits changes to bump version and outputs the new version and commit hash as output
  name: Bump version

  permissions:
    # This is required for requesting the OIDC token
    id-token: write
    # We need to publish a tag
    contents: write

  on:
    workflow_call:
      outputs:
        dev_version:
          value: ${{ jobs.get-new-version.outputs.dev_version }}

  jobs:

    get-new-version:
      name: Get new version string
      runs-on: ubuntu-22.04
      outputs:
        dev_version: ${{ steps.get-new-version.outputs.dev_version }}
      steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up JFrog credentials
        uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
        env:
          JF_URL: https://aerospike.jfrog.io
        with:
          oidc-provider-name: gh-aerospike-clients
          oidc-audience: aerospike/clients

      - name: Install semver library that parses nodejs versions
        # --no-save: prevent package.json or lock file from being changed
        run: npm install --no-save semver
        working-directory: .github/workflows

      - name: Tag new version
        id: get-new-version
        # Can't use "npm version" to bump the dev number. It changes the version in package.json
        # which should only have the current release or expected future release version.
        run: |
          set -e;
          last_tag=$(git describe --tags --abbrev=0)
          echo "Last version tag is $last_tag"

          new_tag=$(node .github/workflows/bump-dev-number-in-version.js "$last_tag");
          git tag $new_tag
          git push origin tag $new_tag
          echo "dev_version=$new_tag" >> $GITHUB_OUTPUT;

          # Update package.json if last tag was a release tag
          current_release_version=$(npm pkg get version | tr -d '"')
          next_release_version=$(node .github/workflows/strip_prerelease_part.js $new_tag)
          if [[ "$current_release_version" != "$next_release_version" ]]; then
            # "npm version" can only commit and tag, or neither at all. But we can't disable one or the other
            npm version patch --no-git-tag-version
            git add -u
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git commit -m "Bump version to $next_release_version"
            git push
          fi
