name: Dev workflow (part 1)

# 1. When a PR review is requested, run tests on that PR
# 2. If all of the tests pass, allow the PR to be merged into `dev`
# 3. Whenever a PR is merged to `dev`, bump version number in `dev`

on:
  pull_request:
    types:
      - review_requested
    branches:
      - 'dev*'
      - 'dev-CICD'
    paths-ignore:
      - 'docs/**'
      - 'aerospike-stubs/**'

  # So we can test changes to the test-server-rc workflow
  workflow_dispatch:
    inputs:
      run_server_release_tests:
        description: 'DEBUG: Run server release tests in build-wheels workflow?'
        type: boolean
        default: false

jobs:
  test-with-server-release:
    uses: ./.github/workflows/build-artifacts.yml
    with:
      run_tests: ${{ github.event_name == 'pull_request' && true || inputs.run_server_release_tests }}
      sha-to-build-and-test: ${{ github.sha }}
    secrets: inherit

  test-with-server-rc:
    needs: test-with-server-release
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'new-server-features') }}
    uses: ./.github/workflows/test-server-rc.yml
    secrets: inherit
