name: 'Build node cpp bindings'
run-name: 'Build node cpp bindings (nodejs-tags=${{ inputs.nodejs-tags }}, platform-tag=${{ inputs.platform-tag }}, run_tests=${{ inputs.run_tests }}, use-server-rc=${{ inputs.use-server-rc }}, server-tag=${{ inputs.server-tag }})'

# Build wheels on all (or select) Python versions supported by the Python client for a specific platform

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:

  workflow_call:
    inputs:
      # See workflow call hack in update-version.yml
      is_workflow_call:
        type: boolean
        default: true
        required: false
      nodejs-tags:
        type: string
        required: false
        default: '[["v115", "20"], ["v127", "22"], ["v137", "24"], ["v141", "25"]]'
      version:
        type: string
        required: true
      platform-tag:
        type: string
        required: true
      run_tests:
        type: boolean
        required: false
        default: false
      use-server-rc:
        required: false
        type: boolean
        default: false
        description: 'Test against server release candidate?'
      server-tag:
        required: false
        type: string
        default: 'latest'
        description: 'Server docker image tag'
      test-file:
        required: false
        type: string
        default: ''
    secrets:
      # Just make all the secrets required to make things simpler...
      soup_hat:
        required: true
      cell_girl:
        required: true
      song_loss:
        required: true

jobs:
  get-runner-os:
    outputs:
      runner-os: ${{ steps.get-runner-os.outputs.runner_os }}
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - id: get-runner-os
      run: |
        declare -A map
        map[manylinux_x86_64]="ubuntu-22.04"
        map[manylinux_aarch64]="ubuntu-22.04-arm"
        map[win_amd64]="windows-2022"
        map[macosx_x86_64]="macos-14-large"
        map[macosx_x86_64_2]="macos-15-large"
        map[macosx_arm64]="macos-14"
        map[macosx_arm64_2]="macos-15"
        echo runner_os=${map[${{ inputs.platform-tag }}]} >> $GITHUB_OUTPUT
      shell: bash


  cibuildbinding:
    needs: get-runner-os
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
      MACOS_OPENSSL_VERSION: 3
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    # - name: Create status check message
    #   run: echo STATUS_CHECK_MESSAGE="cibuildbinding (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
    #   shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - name: Delete workspace
      if: ${{ inputs.platform-tag != 'win_amd64' }}
      run: rm -rf ${{ github.workspace }}/*

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: 'Windows: Install C client deps'
      if: ${{ inputs.platform-tag == 'win_amd64' }}
      run: nuget restore
      working-directory: aerospike-client-c/vs

    - name: 'Install libyaml'
      if: ${{ startsWith(inputs.platform-tag, 'macosx') }}
      run: |
        brew install libyaml

    - if: ${{ startsWith(inputs.platform-tag, 'macosx_arm64') }}
      name: Ensure that linker can find brew packages
      # On mac m1, packages installed via brew are not in the linker's default library path
      run: |
        libraries=('libyaml' 'openssl')
        for library in "${libraries[@]}"; do
          LIBRARY_PATH="${LIBRARY_PATH}:$(brew --prefix $library)/lib"
        done
        echo LIBRARY_PATH=$LIBRARY_PATH >> $GITHUB_ENV
      shell: bash

    - name: Replace AdditionalLibraryDirectories line in props file
      if: ${{ inputs.platform-tag == 'win_amd64' }}
      run: |
        $path = "props\nodejs.props"
        $content = Get-Content $path -Raw
        $pattern = '<AdditionalLibraryDirectories>.*?</AdditionalLibraryDirectories>'
        $basePath = (Resolve-Path .).Path
        $replacement = "<AdditionalLibraryDirectories>`$(NodejsPath);$basePath\packages\openssl-native.3.0.16\lib\win-x64\native;`%(AdditionalIncludeDirectories)</AdditionalLibraryDirectories>"
        $updated = [System.Text.RegularExpressions.Regex]::Replace($content, $pattern, $replacement, 'Singleline')
        Set-Content $path $updated
      working-directory: aerospike-client-c/vs

    - name: Print modified .props file
      if: ${{ inputs.platform-tag == 'win_amd64' }}
      run: |
        Get-Content "props\nodejs.props"
      working-directory: aerospike-client-c/vs

    - name: Change version in package.json
      if: ${{ inputs.platform-tag == 'win_amd64' }}
      run: |
        $v = "${{ env.NEW_VERSION }}"
        Get-Content package.json | jq --arg v $v '.version = $v' | Set-Content package.json
      env:
        NEW_VERSION: ${{ inputs.version }}

    - name: change verison
      if: ${{ inputs.platform-tag != 'win_amd64' }}
      run: |
       npm version ${{ env.NEW_VERSION }} --no-git-tag-version
      env:
        NEW_VERSION: ${{ inputs.new_version }}

    - name: Build Binding
      if: ${{ (startsWith(needs.get-runner-os.outputs.runner-os, 'macos-14') && matrix.nodejs-tag[1] == '25') == false }}
      run: |
        ./scripts/build-c-client.sh;
        npm ci --ignore-scripts;
        npm install @mapbox/node-pre-gyp@2.0.3 --ignore-scripts -g;
        npm run build;
        ls lib/binding;

        node-pre-gyp package
      env:
        NEW_VERSION: ${{ inputs.version }}

    - name: Run tests
      if: ${{ !(inputs.platform-tag == 'macosx_arm64' || inputs.platform-tag == 'win_amd64') }}
      run: |
        cd ts-test;
        npx tsc;
        cd ..;
        npx tsc;
        npm run test dist/${{ inputs.test-file }} -- --h 172.17.0.2 --port 3000 --U superuser --P superuser;

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Upload binding binaries to JFrog Linux x86
      if: ${{ inputs.platform-tag == 'manylinux_x86_64' }}
      run: |
        jf rt upload --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "./node-${{ matrix.nodejs-tag[0] }}-linux-x64/aerospike.node" clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/
      env:
        NEW_VERSION: ${{ inputs.version }}
      working-directory: lib/binding

    - name: Upload binding binaries to JFrog Linux aarch64
      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
      run: |
        jf rt upload --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "./node-${{ matrix.nodejs-tag[0] }}-linux-arm64/aerospike.node" clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/
      env:
        NEW_VERSION: ${{ inputs.version }}
      working-directory: lib/binding

    - name: Upload binding binaries to JFrog darwin x86
      if: ${{ ( matrix.nodejs-tag[1] != '25' && inputs.platform-tag == 'macosx_x86_64' ) }}
      run: |
        jf rt upload --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "./node-${{ matrix.nodejs-tag[0] }}-darwin-x64/aerospike.node" clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/
      env:
        NEW_VERSION: ${{ inputs.version }}
      working-directory: lib/binding

    - name: Upload binding binaries to JFrog darwin x86
      if: ${{ ( matrix.nodejs-tag[1] == '25' && inputs.platform-tag == 'macosx_x86_64_2' ) }}
      run: |
        jf rt upload --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "./node-${{ matrix.nodejs-tag[0] }}-darwin-x64/aerospike.node" clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/
      env:
        NEW_VERSION: ${{ inputs.version }}
      working-directory: lib/binding

    - name: Cleanup Artifacts
      if: ${{ inputs.platform-tag == 'win_amd64' }}
      shell: pwsh
      run: |
        Copy-Item -Path "aerospike-client-c\vs\packages\openssl-native.3.0.16\lib\win-x64\native\libssl.lib" -Destination "build\Release\libssl.lib" -Force
        Copy-Item -Path "aerospike-client-c\vs\packages\openssl-native.3.0.16\lib\win-x64\native\libcrypto.lib" -Destination "build\Release\libcrypto.lib" -Force
        Remove-Item -Recurse -Force .\build\release\obj
        Remove-Item -Force .\build\release\aerospike.pdb
        Remove-Item -Force .\build\release\aerospike.ipdb
        Remove-Item -Force .\build\release\aerospike.iobj

    - name: Upload binding binaries to JFrog windows x86
      if: ${{ inputs.platform-tag == 'win_amd64' }}
      run: |
        jf rt upload --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "./*" clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/node-${{ matrix.nodejs-tag[0] }}-win32-x64/
      env:
        NEW_VERSION: ${{ inputs.version }}
      working-directory: build/Release/

    - name: Upload wheels to GitHub
      if: ${{ inputs.run_tests && (startsWith(inputs.platform-tag, 'macosx_arm64') || inputs.platform-tag == 'win_amd64') }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        path: "./*.tar.gz"
        name: ${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}.build
        if-no-files-found: error

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-self-hosted:
    needs: cibuildbinding
    strategy:
      fail-fast: false
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
    # There's a top-level env variable for this but we can't use it here, unfortunately
    if: ${{ inputs.run_tests && (startsWith(inputs.platform-tag, 'macosx_arm64') || inputs.platform-tag == 'win_amd64') }}
    runs-on: ${{ startsWith(inputs.platform-tag, 'macosx_arm64') && fromJSON('["self-hosted", "macOS", "ARM64"]') || fromJSON('["self-hosted", "Windows", "X64"]') }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0

      # Need to be able to save Docker Hub credentials to keychain
      # Unable to do this via the ansible script for self hosted mac m1 runners
      - if: ${{ inputs.platform-tag == 'macosx_arm64' }}
        run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}

      - name: Download binding
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}.build

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.nodejs-tag[1] }}

      - run: npm install *.tar.gz

      - name: Run tests
        run: |
          cd ts-test;
          npx tsc;
          cd ..;
          npx tsc;
          npm run test dist/${{ inputs.test-file }} -- --h 172.17.0.2 --port 3000 --U superuser --P superuser;

      - name: Upload binding binaries to JFrog darwin aarch64
        run: |
          jf rt upload --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "./node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/aerospike.node" clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/
        env:
          NEW_VERSION: ${{ inputs.version }}
        working-directory: lib/binding
