# As of this writing, there are no Github Actions in the marketplace
# that allow fast forwarding using a personal access token
# So we need to use this for now
name: 'Fast forward merge'
on:
  workflow_dispatch:
    inputs:
      ref_to_merge:
        type: string
        required: true
      base_branch:
        type: string
        required: true
  workflow_call:
    inputs:
      # If another branch, it must be origin/<branch>
      ref_to_merge:
        type: string
        required: true
      base_branch:
        type: string
        required: true

jobs:
  merge:
    runs-on: ubuntu-22.04
    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Fetch the whole history to prevent unrelated history errors
          fetch-depth: '0'
          ref: ${{ inputs.base_branch }}

      - name: Fast forward
        run: git merge --ff-only ${{ inputs.ref_to_merge }}

      - name: Upload changes to remote head branch
        run: git push
