# Takes in how to bump version as input
# Commits changes to bump version and outputs the new version and commit hash as output
name: Bump version

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  contents: read

on:
  workflow_call:
    outputs:
      stage_version:
        value: ${{ jobs.get-jfrog-stage-version.outputs.stage_version }}
      bump_sha:
        value: ${{ jobs.update-version-in-repo.outputs.bump_sha }}

jobs:
  get-jfrog-stage-version:
    name: Get most recent JFrog version string
    runs-on: ubuntu-22.04
    outputs:
      stage_version: ${{ steps.get-jfrog-stage-version.outputs.stage_version }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    # Checkout the branch where we want to bump the new version
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@893a92f96c7727242adf0e603c77b1f2a22390e1 # v4.9.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Get jfrog version
      id: get-jfrog-stage-version
      run: |
        echo "stage_version=$(jfrog rt s "clients-npm-stage-local/aerospike/*" | jq -r '.[]?.path | capture("aerospike/(?<version>[^/]+)") | .version' | grep -v '^-$' | grep -v '^lib$' | sort -V | grep -v 'dev' | tail -n1)" >> $GITHUB_OUTPUT

    - name: Print jfrog version
      run: echo "Jfrog version is ${{ steps.get-jfrog-stage-version.outputs.stage_version }}"