# Takes in how to bump version as input
# Commits changes to bump version and outputs the new version and commit hash as output
name: Bump version

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      ref:
        required: false
        description: Commit to bump off of
        type: string
    outputs:
      stage_version:
        value: ${{ jobs.master-get-jfrog-version.outputs.stage_version }}

jobs:
  master-get-jfrog-version:
    name: Get most recent JFrog version string
    runs-on: ubuntu-22.04
    outputs:
      stage_version: ${{ steps.master-get-jfrog-version.outputs.stage_version }}
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    # Checkout the branch where we want to bump the new version
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Get jfrog version
      id: master-get-jfrog-version
      run: |
        echo "stage_version=$(jfrog rt s "clients-npm-stage-local/aerospike/*" | jq -r '.[]?.path | capture("aerospike/(?<version>[^/]+)") | .version' | grep -v '^-$' | grep -v '^lib$' | sort -V | grep -v 'dev' | tail -n1)" >> $GITHUB_OUTPUT

    - name: Print jfrog version
      run: echo "Jfrog version is ${{ steps.master-get-jfrog-version.outputs.stage_version }}"
