name: Master workflow
permissions: 
  contents: read

on:
  push:
    branches:
      - stage

jobs:
  master-get-jfrog-version:
    uses: ./.github/workflows/master-get-jfrog-version.yml
    secrets: inherit

  bump-master-number:
    uses: ./.github/workflows/master-bump-version.yml
    needs: [
      master-get-jfrog-version,
    ]
    secrets: inherit

  publish-to-npm:
    name: Publish to npm
    needs: [
      master-get-jfrog-version,
      bump-master-number,
    ]
    uses: ./.github/workflows/master-upload-jfrog-build-to-npm.yml
    with:
      old_version: ${{ needs.master-get-jfrog-version.outputs.stage_version }}
      new_version: ${{ needs.bump-master-number.outputs.new_master_version }}
    secrets: inherit

  verify-npm-install:
    name: verify npm clean install works correctly
    needs: [
      master-get-jfrog-version,
      bump-master-number,
      publish-to-npm
    ]
    uses: ./.github/workflows/master-verify-npm-install.yml
    with:
      new_version: ${{ needs.bump-master-number.outputs.new_master_version }}
    secrets: inherit

  #reupload-master-to-jfrog:
  #  name: Upload artifacts to JFrog
  #  needs: [
  #    master-get-jfrog-version,
  #    bump-master-number,
  #    publish-to-npm,
  #    verify-npm-install
  #  ]
  #  uses: ./.github/workflows/shared-reupload-addons-to-jfrog.yml
  #  with:
  #    old_version: ${{ needs.master-get-jfrog-version.outputs.stage_version }}
  #    new_version: ${{ needs.bump-master-number.outputs.new_master_version }}
  #    pipeline-stage: 'master'
  #  secrets: inherit
#
  #reupload-master-to-jfrog-npm-repo:
  #  name: Upload artifacts to JFrog
  #  needs: [
  #    master-get-jfrog-version,
  #    bump-master-number,
  #    publish-to-npm,
  #    verify-npm-install,
  #    reupload-master-to-jfrog
  #  ]
  #  uses: ./.github/workflows/shared-upload-npm-package-to-jfrog.yml
  #  with:
  #    new_version: ${{ needs.bump-master-number.outputs.new_master_version }}
  #    pipeline-stage: 'master'
  #  secrets: inherit

#
#  ff-master-to-stage:
#    uses: ./.github/workflows/fast-forward-merge.yml
#    needs: [
#      get-jfrog-stage-version,
#      bump-dev-number,
#      reupload-stage-to-jfrog,
#      publish-to-npm
#    ]
#    with:
#      ref_to_merge: origin/stage-CICD
#      base_branch: master-test
#    secrets: inherit
#
#  ff-stage-to-dev:
#    uses: ./.github/workflows/fast-forward-merge.yml
#    needs: [
#      get-jfrog-stage-version,
#      bump-dev-number,
#      reupload-stage-to-jfrog,
#      publish-to-npm
#    ]
#    with:
#      ref_to_merge: origin/dev
#      base_branch: stage
#    secrets: inherit

