# Takes in how to bump version as input
# Commits changes to bump version and outputs the new version and commit hash as output

name: Bump version

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      ref:
        required: false
        description: Commit to bump off of
        type: string
      # See workflow call hack in update-version.yml
      is_workflow_call:
        type: boolean
        default: true
        required: false
    outputs:
      new_master_version:
        value: ${{ jobs.get-new-master-version.outputs.new_master_version }}
      bump_sha:
        value: ${{ jobs.update-version-in-repo.outputs.bump_sha }}

jobs:
  get-next-master-jfrog-version:
    name: Get most recent JFrog version string
    runs-on: ubuntu-22.04
    outputs:
      master_version: ${{ steps.get-next-master-jfrog-version.outputs.master_version }}
    steps:
    # Checkout the branch where we want to bump the new version
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up JFrog credentials
      uses: jfrog/setup-jfrog-cli@88e9eba31c07e31beefa4cef5c0e93d1af9535d7 # v4.6.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Get jfrog version
      id: get-next-master-jfrog-version
      run: |
        echo "master_version=$(jfrog rt s "clients-npm-stage-local/aerospike/*" | jq -r '.[]?.path | capture("aerospike/(?<version>[^/]+)") | .version' | grep -v '^-$' | grep -v '^lib$' | sort -V | tail -n1)" >> $GITHUB_OUTPUT

    - name: Print jfrog version
      run: echo "Jfrog version is ${{ steps.get-next-master-jfrog-version.outputs.master_version }}"

  get-new-master-version:
    runs-on: ubuntu-22.04
    needs: [
      get-next-master-jfrog-version
    ]
    outputs:
      new_master_version: ${{ steps.get-new-version.outputs.new_master_version }}
    steps:

    # Checkout the branch where we want to bump the new version
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install library that parses nodejs versions
    # NEED TO CHANGE THIS TO WORK WITH NODEJS
      run: npm install semver@7.7.2
      working-directory: .github/workflows

    - name: Get new version
      id: get-new-version
      run: |
        set -e
        new_master_version=$( node master-bump-version.js ${{ needs.get-next-master-jfrog-version.outputs.master_version }} )
        echo "new_master_version=$new_master_version" >> $GITHUB_OUTPUT
      working-directory: .github/workflows

    - name: Print new version
      run: |
        echo "${{ steps.get-new-version.outputs.new_master_version }}"