name: 'Donwload github artifacts'
description: 'Download github artifacts for all supported versions'

on:
  workflow_call:
    inputs:
      nodejs-tags:
        type: string
        required: false
        default: '[["v115", "20"], ["v127", "22"], ["v137", "24"], ["v141", "25"]]'
      new_version:
        type: string
        required: true
      scenario:
        type: string
        required: true
jobs:
  run-npm-install-and-require-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14-large, macos-15-large, SMA2, SMA3, windows-2022]
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Delete workspace
        if: ${{ matrix.os != 'windows-2022' }}
        run: rm -rf ${{ github.workspace }}/*

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.nodejs-tag[1] }}

      - name: verify runs and is aligned with expect functionality
        if: ${{ inputs.scenario == 'omitscripts' }}
        run: |
          npm install fakospike@${{ env.NEW_VERSION }} --omit=dev --ignore-scripts;
          node ./node_modules/fakospike/scripts/verify-fakospike-npm-scripts.js fakospike;
          npx --package fakospike npm run removeExtraBinaries --prefix ./node_modules/fakospike;
          npx --package fakospike npm run build --prefix ./node_modules/fakospike;
          node -e "const fakospike = require('fakospike'); console.log(fakospike.exp.unknown());"
        env:
          NEW_VERSION: ${{ inputs.new_version }}

      - name: verify runs and is aligned with expect functionality
        if: ${{ inputs.scenario  == 'omitdev'  }}
        run: |
          npm install fakospike@${{ env.NEW_VERSION }} --omit=dev;
          node -e "const fakospike = require('fakospike'); console.log(fakospike.exp.unknown());"
        env:
          NEW_VERSION: ${{ inputs.new_version }}

      - name: verify runs and is aligned with expect functionality
        if: ${{ inputs.scenario  == 'omitnone'  }}
        run: |
          npm install fakospike@${{ env.NEW_VERSION }};
          node -e "const fakospike = require('fakospike'); console.log(fakospike.exp.unknown());"
        env:
          NEW_VERSION: ${{ inputs.new_version }}