name: 'Donwload github artifacts'
description: 'Download github artifacts for all supported versions'

on:
  workflow_call:
    inputs:
      nodejs-tags:
        type: string
        required: false
        default: '[["v115", "20"], ["v127", "22"], ["v137", "24"]]'
      new_version:
        type: string
        required: true
jobs:
  run-npm-install-and-require-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-13-large, SMA2, windows-2022]
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Delete workspace
        if: ${{ matrix.os != 'windows-2022' }}
        run: rm -rf ${{ github.workspace }}/*

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-tag[1] }}

      - name: verify runs and is aligned with expect functionality
        run: |
          npm init -y;
          jq '.dependencies.ad2="${{ env.NEW_VERSION }}"' "package.json" > tmp.$$.json && mv tmp.$$.json "package.json";
          npm install --production --ignore-scripts;
          node ./node_modules/ad2/scripts/verify-aerospike-npm-scripts.js ad2;
          npx --package ad2 npm run install --prefix ./node_modules/ad2;
          node -e "const Aerospike = require('ad2'); console.log(new Aerospike.BasePolicy({ connectTimeout: 4000, timeoutDelay: 3500 }));"
        env:
          NEW_VERSION: ${{ inputs.new_version }}