name: Publish JFrog build to NPM

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      old_version:
        type: string
        required: false
      new_version:
        type: string
        required: false
    secrets:
      NPMRC_RELEASE:
        required: true
      AUTH_TOKEN:
        required: true

jobs:
  publish-jfrog-build-to-npm:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}
        registry-url: 'https://registry.npmjs.org'

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.new_version }}.tgz" .

    # - name: Download Artifacts from Jfrog
    #   run: jf rt dl "clients-npm-stage-local/aerospike/${{ env.OLD_VERSION }}/" "downloaded-artifacts/"
    #   env:
    #     OLD_VERSION: ${{ inputs.old_version }}
    #     PACKAGE_MANAGER: npm

    # - name: Move artifacts
    #   run: |
    #     tar --strip-components=1 -xvf aerospike-${{ env.OLD_VERSION }}.tgz;
    #   env:
    #     OLD_VERSION: ${{ inputs.old_version }}
    #   working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    #- name: change package name
    #  run: |
    #    sed -i 's/"name": "[^"]*"/"name": "fakospike"/' package.json
    #  working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    # - name: change verison
    #   run: |
    #    npm version ${{ env.NEW_VERSION }} --no-git-tag-version
    #   env:
    #     NEW_VERSION: ${{ inputs.new_version }}
    #   working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    - name: prepare install
      run: |
        node ./scripts/change-install-command.js;
      env:
        OLD_VERSION: ${{ inputs.old_version }}
      # working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    - name: npm rc
      run: echo "$NPMRC" | base64 --decode > ~/.npmrc  
      env:
        NPMRC: ${{ secrets.NPMRC_RELEASE }}

    - run: |
        # cp ../../../package-lock.json package-lock.json;
        # npm ci --ignore-scripts;
        npm publish *.tgz --provenance;
      env:
        NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      # working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}
