name: Build Node C++ Addons
run-name: Build Node C++ Addons (run_tests=${{ inputs.run_tests }}, use-server-rc=${{ inputs.use-server-rc }}, server-tag=${{ inputs.server-tag }})

# Builds native prebuilds
# Optionally run tests on prebuilds
# Then upload artifacts to Github


on:
  workflow_call:
    inputs:
      # The "dev" tests test the artifacts against a server
      # The dev-to-stage and stage-to-master workflow only need to build the artifacts, not test them
      run_tests:
        required: false
        type: boolean
        default: false
      server-tag:
        type: string
        required: false
        default: 'latest'
    secrets:
      soup_hat:
        required: true
      cell_girl:
        required: true
      song_loss:
        required: true

jobs:
  build-node-cpp-bindings:
    strategy:
      matrix:
        platform-tag: [
          "linux_x86_64",
          "linux_aarch64",
          "darwin_x86_64",
          "darwin_x86_64_2",
          "darwin_arm64",
          "darwin_arm64_2",
          "win32_x64"
        ]
      fail-fast: false
    uses: ./.github/workflows/master-build-node-cpp-bindings.yml
    with:
      platform-tag: ${{ matrix.platform-tag }}
      run_tests: ${{ inputs.run_tests }}
      server-tag: ${{ inputs.server-tag }}
    secrets:
      soup_hat: ${{ secrets.soup_hat }}
      cell_girl: ${{ secrets.cell_girl }}
      song_loss: ${{ secrets.song_loss }}