name: npm install script test

on:
  workflow_call: # This allows this workflow to be reused by others.

jobs:
  npm-install-script-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create multiple directories
        run: mkdir -p ./lib/binding ./lib/binding/glibc@2.35/ ./lib/binding/glibc@2.31/

      # MAC X86
      - uses: actions/download-artifact@v4
        with:
          name: v108-macosx_x86_64.node
          path: ./lib/binding/node-v108-darwin-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v115-macosx_x86_64.node
          path: ./lib/binding/node-v115-darwin-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v127-macosx_x86_64.node
          path: ./lib/binding/node-v127-darwin-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v131-macosx_x86_64.node
          path: ./lib/binding/node-v131-darwin-x64/

      # MAC ARM
      #- uses: actions/download-artifact@v4
      #  with:
      #    name: v108-macosx_x86_64.node
      #    path: ./lib/binding/node-v108-darwin-arm64/

      #- uses: actions/download-artifact@v4
      #  with:
      #    name: v115-macosx_x86_64.node
      #    path: ./lib/binding/node-v115-darwin-arm64/

      #- uses: actions/download-artifact@v4
      #  with:
      #    name: v127-macosx_x86_64.node
      #    path: ./lib/binding/node-v127-darwin-arm64/

      #- uses: actions/download-artifact@v4
      #  with:
      #    name: v131-macosx_x86_64.node
      #    path: ./lib/binding/node-v131-darwin-arm64/

      # Linux X86
      - uses: actions/download-artifact@v4
        with:
          name: v108-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v108-linux-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v115-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v115-linux-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v127-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v127-linux-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v131-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v131-linux-x64/

      ## Linux ARM
      - uses: actions/download-artifact@v4
        with:
          name: v108-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v108-linux-arm64/

      - uses: actions/download-artifact@v4
        with:
          name: v115-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v115-linux-arm64/


      - uses: actions/download-artifact@v4
        with:
          name: v127-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v127-linux-arm64/

      - uses: actions/download-artifact@v4
        with:
          name: v131-manylinux_x86_64.node
          path: ./lib/binding/glibc@2.31/node-v131-linux-arm64/

      # Windows
      - uses: actions/download-artifact@v4
        with:
          name: v108-manylinux_x86_64.node
          path: ./lib/binding/node-v108-win32-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v115-manylinux_x86_64.node
          path: ./lib/binding/node-v115-win32-x64/


      - uses: actions/download-artifact@v4
        with:
          name: v127-manylinux_x86_64.node
          path: ./lib/binding/node-v127-win32-x64/

      - uses: actions/download-artifact@v4
        with:
          name: v131-manylinux_x86_64.node
          path: ./lib/binding/node-v131-win32-x64/

      - name: Install client
        shell: bash
        run: |
          ls .;
          echo "BINDING FOLDER:";
          ls ./lib/binding;
          mkdir -p lib/binding/glibc@2.35/node-v108-darwin-x64 lib/binding/glibc@2.35/node-v115-darwin-x64 lib/binding/glibc@2.35/node-v127-darwin-x64 lib/binding/glibc@2.35/node-v131-darwin-x64;
          mkdir -p lib/binding/glibc@2.35/node-v108-linux-x64 lib/binding/glibc@2.35/node-v115-linux-x64 lib/binding/glibc@2.35/node-v127-linux-x64 lib/binding/glibc@2.35/node-v131-linux-x64;
  #        echo "BINDING FOLDER:";
  #        mkdir -p lib/binding/node-v108-darwin-arm64 lib/binding/node-v115-darwin-arm64 lib/binding/node-v127-darwin-arm64 lib/binding/node-v131-darwin-arm64
  #        mkdir -p lib/binding/glibc@2.31/node-v108-linux-arm64 lib/binding/glibc@2.31/node-v115-linux-arm64 lib/binding/glibc@2.31/node-v127-linux-arm64 lib/binding/glibc@2.35/node-v131-linux-arm64
  #        mkdir -p lib/binding/glibc@2.35/node-v108-linux-x64 lib/binding/glibc@2.35/node-v115-linux-x64 lib/binding/glibc@2.35/node-v127-linux-x64 lib/binding/glibc@2.35/node-v131-linux-x64
  #        mkdir -p lib/binding/glibc@2.31/node-v108-linux-x64 lib/binding/glibc@2.31/node-v115-linux-x64 lib/binding/glibc@2.31/node-v127-linux-x64 lib/binding/glibc@2.31/node-v131-linux-x64
  #        cp -r node-v108-linux-x64 lib/binding/glibc@2.35/
  #        cp -r node-v115-linux-x64 lib/binding/glibc@2.35/
  #        cp -r node-v127-linux-x64 lib/binding/glibc@2.35/
  #        cp -r node-v108-darwin-x64 lib/binding/node-v108-darwin-x64
  #        cp -r node-v115-darwin-x64 lib/binding/node-v115-darwin-x64
  #        cp -r node-v127-darwin-x64 lib/binding/node-v127-darwin-x64
  #        cp -r node-v131-darwin-x64 lib/binding/node-v131-darwin-x64
  #        cp -r node-v108-linux-arm64 lib/binding/node-v108-linux-arm64
  #        cp -r node-v115-linux-arm64 lib/binding/node-v115-linux-arm64
  #        cp -r node-v127-linux-arm64 lib/binding/node-v127-linux-arm64
  #        cp -r node-v127-linux-arm64 lib/binding/node-v131-linux-arm64
  #        cp -r node-v108-darwin-arm64 lib/binding/node-v108-darwin-arm64
  #        cp -r node-v115-darwin-arm64 lib/binding/node-v115-darwin-arm64
  #        cp -r node-v127-darwin-arm64 lib/binding/node-v127-darwin-arm64
  #        cp -r node-v127-darwin-arm64 lib/binding/node-v131-darwin-arm64

      - name: List available artifacts
        run: ls ./lib/binding || echo "No artifacts found in binding"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set version
        run: npm version 6.0.1-dev.1 --no-git-tag-version

      - name: Change install command for release
        run: node ./scripts/change-install-command.js

      - name: verdaccio server run
        run: |
          docker run --rm -d --name verdaccio -p 4873:4873 verdaccio/verdaccio
          curl http://0.0.0.0:4873/
          npm adduser --registry http://0.0.0.0:4873/
          npm publish --registry http://0.0.0.0:4873/

      #- name: List available artifacts
      #  run: ls ./lib/binding || echo "No artifacts found in binding"