name: npm install script test

on:
  workflow_call: # This allows this workflow to be reused by others.

jobs:
  npm-install-script-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Create multiple directories
        run: mkdir -p ./lib/binding ./lib/binding/glibc@2.35/ ./lib/binding/glibc@2.31

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v108-manylinux_x86_64
          path: ./lib/binding/glibc@2.35/

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v108-macosx_x86_64
          path: ./lib/binding

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v115-manylinux_x86_64
          path: ./lib/binding/glibc@2.35/

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v115-macosx_x86_64
          path: ./lib/binding

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v127-manylinux_x86_64
          path: ./lib/binding/glibc@2.35/

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v127-macosx_x86_64
          path: ./lib/binding

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v131-manylinux_x86_64
          path: ./lib/binding/glibc@2.35/

      - name: Download wheels from GitHub
        uses: actions/download-artifact@v4
        with:
          name: v131-macosx_x86_64
          path: ./lib/binding


      - name: List available artifacts
        run: ls ./lib/binding || echo "No artifacts found in binding"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run Node.js script
        run: node ./scripts/prebuiltBinding.js

      - name: List available artifacts
        run: ls ./lib/binding || echo "No artifacts found in binding"