name: npm install script test

on:
  workflow_call: # This allows this workflow to be reused by others.

jobs:
  npm-install-script-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Create multiple directories
        run: mkdir -p ./lib/binding ./lib/binding/glibc@2.35/ ./lib/binding/glibc@2.31



  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: v108-macosx_aarch64.build

      - uses: actions/download-artifact@v4
        with:
          name: v108-macosx_x86_64.node

  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: v115-macosx_aarch64.build

      - uses: actions/download-artifact@v4
        with:
          name: v115-macosx_x86_64.node

  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: v127-macosx_aarch64.build

      - uses: actions/download-artifact@v4
        with:
          name: v127-macosx_x86_64.node

      - uses: actions/download-artifact@v4
        with:
          name: v131-macosx_x86_64.node

      - uses: actions/download-artifact@v4
        with:
          name: v108-manylinux_x86_64.node

  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: v108-manylinux_aarch64.build

      - uses: actions/download-artifact@v4
        with:
          name: v115-manylinux_x86_64.node

  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: v115-manylinux_aarch64.build

      - uses: actions/download-artifact@v4
        with:
          name: v127-manylinux_x86_64.node

  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: v127-manylinux_aarch64.build

      - uses: actions/download-artifact@v4
        with:
          name: v131-manylinux_x86_64.node

  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: v131-manylinux_aarch64.build

      - name: Install client
        shell: bash
        run: |
          mkdir -p lib/binding/node-v108-darwin-arm64 lib/binding/node-v115-darwin-arm64 lib/binding/node-v127-darwin-arm64 lib/binding/node-v131-darwin-arm64
          mkdir -p lib/binding/glibc@2.39/node-v108-linux-arm64 lib/binding/glibc@2.39/node-v115-linux-arm64 lib/binding/glibc@2.39/node-v127-linux-arm64 lib/binding/glibc@2.39/node-v131-linux-arm64
          mkdir -p lib/binding/glibc@2.35/node-v108-linux-arm64 lib/binding/glibc@2.35/node-v115-linux-arm64 lib/binding/glibc@2.35/node-v127-linux-arm64 lib/binding/glibc@2.31/node-v131-linux-arm64
          mkdir -p lib/binding/glibc@2.31/node-v108-linux-arm64 lib/binding/glibc@2.31/node-v115-linux-arm64 lib/binding/glibc@2.31/node-v127-linux-arm64 lib/binding/glibc@2.35/node-v131-linux-arm64
          mkdir -p lib/binding/glibc@2.39/node-v108-linux-x64 lib/binding/glibc@2.39/node-v115-linux-x64 lib/binding/glibc@2.39/node-v127-linux-x64 lib/binding/glibc@2.39/node-v131-linux-x64
          mkdir -p lib/binding/glibc@2.35/node-v108-linux-x64 lib/binding/glibc@2.35/node-v115-linux-x64 lib/binding/glibc@2.35/node-v127-linux-x64 lib/binding/glibc@2.35/node-v131-linux-x64
          mkdir -p lib/binding/glibc@2.31/node-v108-linux-x64 lib/binding/glibc@2.31/node-v115-linux-x64 lib/binding/glibc@2.31/node-v127-linux-x64 lib/binding/glibc@2.31/node-v131-linux-x64
          cp -r node-v108-linux-x64 lib/binding/glibc@2.35/
          cp -r node-v115-linux-x64 lib/binding/glibc@2.35/
          cp -r node-v127-linux-x64 lib/binding/glibc@2.35/
          cp -r node-v108-darwin-x64 lib/binding/node-v108-darwin-x64
          cp -r node-v115-darwin-x64 lib/binding/node-v115-darwin-x64
          cp -r node-v127-darwin-x64 lib/binding/node-v127-darwin-x64
          cp -r node-v127-darwin-x64 lib/binding/node-v131-darwin-x64
  #        cp -r node-v108-linux-arm64 lib/binding/node-v108-linux-arm64
  #        cp -r node-v115-linux-arm64 lib/binding/node-v115-linux-arm64
  #        cp -r node-v127-linux-arm64 lib/binding/node-v127-linux-arm64
  #        cp -r node-v127-linux-arm64 lib/binding/node-v131-linux-arm64
  #        cp -r node-v108-darwin-arm64 lib/binding/node-v108-darwin-arm64
  #        cp -r node-v115-darwin-arm64 lib/binding/node-v115-darwin-arm64
  #        cp -r node-v127-darwin-arm64 lib/binding/node-v127-darwin-arm64
  #        cp -r node-v127-darwin-arm64 lib/binding/node-v131-darwin-arm64

      - name: List available artifacts
        run: ls ./lib/binding || echo "No artifacts found in binding"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run Node.js script
        run: node ./scripts/prebuiltBinding.js

      - name: List available artifacts
        run: ls ./lib/binding || echo "No artifacts found in binding"