name: Release workflow

on:
  workflow_call:
  workflow_dispatch:
    paths-ignore:
      - 'package.json'

jobs:
  bump-dev-number:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'bump-dev-num'
    secrets: inherit

  rebuild-artifacts-with-new-dev-num:
    name: Rebuild artifacts
    uses: ./.github/workflows/build-artifacts.yml
    with:
      # On pull_request_target, the bump version commit will be ignored
      # So we must pass it manually to the workflow
      run-tests: false;
      sha-to-build-and-test: ${{ needs.bump-dev-number.outputs.bump_sha }}
    secrets: inherit

  test-npm-install:
    needs: rebuild-artifacts-with-new-dev-num
    name: Test npm install command for npm package
    uses: ./.github/workflows/npm-install-script-test.yml

#  upload-to-jfrog:
#    name: Upload artifacts to JFrog
#    needs: [
#      bump-dev-number,
#      rebuild-artifacts-with-new-dev-num
#    ]
#    uses: ./.github/workflows/upload-to-jfrog.yml
#    with:
#      version: ${{ needs.bump-dev-number.outputs.new_version }}
#    secrets: inherit
#
#  # We don't want the artifacts in JFrog to also exist in Github
#  delete-artifacts:
#    needs: upload-to-jfrog
#    uses: ./.github/workflows/delete-artifacts.yml
#