name: 'Donwload github artifacts'
description: 'Download github artifacts for all supported versions'

on:
  workflow_call:
    inputs:
      nodejs-tags:
        type: string
        required: false
        default: '[["v108", "18"], ["v115", "20"], ["v127", "22"], ["v131", "23"]]'
      platform-tag:
        type: string
        required: true


jobs:
  run-npm-install-and-require-test:
    needs: get-runner-os
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-tag[1] }}

      - name: verify runs and is aligned
        run: |
          npm install xyzparbart;
          node -e "console.log(require('xyzparbart').Transaction.commitStatus)";