name: Upload to JFrog

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_dispatch:
    inputs:
      old_version:
        type: string
        required: false
      new_version:
        type: string
        required: false
      pipeline-stage:
        type: string
        required: true
  workflow_call:
    inputs:
      old_version:
        type: string
        required: false
      new_version:
        type: string
        required: false
      pipeline-stage:
        type: string
        required: true
      jfrog-repo-name:
        type: string
        required: false
        default: ${{ vars.JFROG_REPO_NAME }}

jobs:
  upload-to-jfrog:
    name: Upload artifacts to JFrog
    env:
      JFROG_RELEASE_BUNDLE_NAME: aerospike-nodejs-client
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@893a92f96c7727242adf0e603c77b1f2a22390e1 # v4.9.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Download Artifacts from Jfrog
      if: ${{ inputs.pipeline-stage == 'stage' }}
      run: jf rt dl "database-npm-dev-local/aerospike/${{ env.OLD_VERSION }}/" "downloaded-artifacts/"
      env:
        OLD_VERSION: ${{ inputs.old_version }}
        PACKAGE_MANAGER: npm

    - name: Download Artifacts from Jfrog
      if: ${{ inputs.pipeline-stage == 'master' }}
      run: jf rt dl "clients-npm-stage-local/aerospike/${{ env.OLD_VERSION }}/" "downloaded-artifacts/"
      env:
        OLD_VERSION: ${{ inputs.old_version }}
        PACKAGE_MANAGER: npm

    - name: Move artifacts
      run: |
        tar --strip-components=1 -xvf aerospike-${{ env.OLD_VERSION }}.tgz
      env:
        OLD_VERSION: ${{ inputs.old_version }}
      working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    - name: list version info
      run: 
        cp ../../../package-lock.json package-lock.json;
        npm version ${{ env.NEW_VERSION }} --no-git-tag-version;
        npm ci --ignore-scripts;
        npm pack;
      env:
        NEW_VERSION: ${{ inputs.new_version }}
      working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    - name: Upload passing builds to JFrog Nodejs repo
      if: ${{ inputs.pipeline-stage == 'stage' }}
    # Source path must be in quotes if it contains an asterisk
      # https://github.com/jfrog/jfrog-cli/issues/1775#issuecomment-1348986551
      run: jf rt upload --project database --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "aerospike-${{ env.NEW_VERSION }}.tgz" clients-npm-stage-local/aerospike/${{ env.NEW_VERSION }}/
      env:
        NEW_VERSION: ${{ inputs.new_version }}
      working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    - name: Upload passing builds to JFrog Nodejs repo
      if: ${{ inputs.pipeline-stage == 'master' }}
    # Source path must be in quotes if it contains an asterisk
      # https://github.com/jfrog/jfrog-cli/issues/1775#issuecomment-1348986551
      run: jf rt upload --project database --build-name nodejs-client --build-number ${{ env.NEW_VERSION }} "aerospike-${{ env.NEW_VERSION }}.tgz" database-npm-prod-public-local/aerospike/${{ env.NEW_VERSION }}/
      env:
        NEW_VERSION: ${{ inputs.new_version }}
      working-directory: downloaded-artifacts/aerospike/${{ inputs.old_version }}

    - name: Publish build info
      run: jf rt build-publish --project database nodejs-client ${{ inputs.new_version }}

    # Required to run sponge
    - run: sudo apt install -y moreutils

    # .files.project is not documented in JFrog but it's used to specify the JFrog project to upload this release bundle to
    - name: Create file spec for release bundle
      run: cat releasebundle-filespec.json | jq '.files[0].build = "nodejs-client/${{ inputs.new_version }}"' | sponge releasebundle-filespec.json
      working-directory: .github/workflows
      shell: bash

    - name: Create release bundle from JFrog build
      # Not the same name as in proxy/pom.xml
      # But that name doesn't specify the language,
      # and there can be multiple languages that implement the proxy client in the future that need to be uploaded to JFrog
      # Signing key only signs release bundle and not the artifacts associated with it
      run: jf release-bundle-create --project database --signing-key=aerospike --sync --spec=./releasebundle-filespec.json ${{ env.JFROG_RELEASE_BUNDLE_NAME }} ${{ inputs.new_version }}
      working-directory: .github/workflows

    - name: Promote release bundle to STAGE stage
      if: ${{ inputs.pipeline-stage == 'stage' }}
      run: jf release-bundle-promote --project database --signing-key=aerospike --sync ${{ env.JFROG_RELEASE_BUNDLE_NAME }} ${{ inputs.new_version }} STAGE
      working-directory: .github/workflows

    - name: Promote release bundle to PROD stage
      if: ${{ inputs.pipeline-stage == 'master' }}
      run: jf release-bundle-promote --project database --signing-key=aerospike --sync ${{ env.JFROG_RELEASE_BUNDLE_NAME }} ${{ inputs.new_version }} PROD
      working-directory: .github/workflows
