name: Upload to JFrog npm repository

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_call:
    inputs:
      new_version:
        type: string
        required: true
      pipeline-stage:
        type: string
        required: false
      jfrog-repo-name:
        type: string
        required: false
        default: ${{ vars.JFROG_REPO_NAME }}
      #oidc-provider:
      #  type: string
      #  description: ""
      #  required: false
      #  default: gh-aerospike-clients
      #oidc-audience:
      #  type: string
      #  description: ""
      #  required: false
      #  default: aerospike/clients
    secrets:
      plane_grass:
        required: false
      aisle_thank:
        required: false
      room_lane:
        required: false

jobs:
  upload-to-jfrog:
    name: Upload artifacts to JFrog
    env:
      JFROG_RELEASE_BUNDLE_NAME: aerospike-nodejs-client
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Download Artifacts from Jfrog
      if: ${{ inputs.pipeline-stage == 'dev' }}
      run: jf rt dl "clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/" "downloaded-artifacts/"
      env:
        NEW_VERSION: ${{ inputs.new_version }}
        PACKAGE_MANAGER: npm

    - name: Download Artifacts from Jfrog
      if: ${{ inputs.pipeline-stage == 'stage' }}
      run: jf rt dl "clients-npm-stage-local/aerospike/${{ env.NEW_VERSION }}/" "downloaded-artifacts/"
      env:
        NEW_VERSION: ${{ inputs.new_version }}
        PACKAGE_MANAGER: npm

    - name: Download Artifacts from Jfrog
      if: ${{ inputs.pipeline-stage == 'master' }}
      run: jf rt dl "clients-npm-prod-public-local/aerospike/${{ env.NEW_VERSION }}/" "downloaded-artifacts/"
      env:
        NEW_VERSION: ${{ inputs.new_version }}
        PACKAGE_MANAGER: npm

    - name: Move artifacts
      run: |
        tar --strip-components=1 -xvf aerospike-${{ env.NEW_VERSION }}.tgz
      env:
        NEW_VERSION: ${{ inputs.new_version }}
      working-directory: downloaded-artifacts/aerospike/${{ inputs.new_version }}

    - name: Update version in package.json
      run: 
        jq --arg v "${{ env.VERSION }}" '.version = $v' package.json > tmp.json && mv tmp.json package.json;
      env:
        VERSION: ${{ inputs.new_version }} 

    - name: Install dependencies and test install
      run:
        npm ci --ignore-scripts;

    - name: prepare to publish dev npm package to Jfrog
      if: ${{ inputs.pipeline-stage == 'dev' }}
      run: |
        echo "$plane_grass" | base64 --decode > ~/.npmrc  
      env:
        plane_grass: ${{ secrets.plane_grass }}

    - name: prepare to publish stage npm package to Jfrog
      if: ${{ inputs.pipeline-stage == 'stage' }}
      run: |
        echo "$aisle_thank" | base64 --decode > ~/.npmrc  
      env:
        aisle_thank: ${{ secrets.aisle_thank }}

    - name: prepare to publish master npm package to Jfrog
      if: ${{ inputs.pipeline-stage == 'master' }}
      run: |
        echo "$room_lane" | base64 --decode > ~/.npmrc  
      env:
        room_lane: ${{ secrets.room_lane }}

    - name: publish npm package to Jfrog dev repository
      if: ${{ inputs.pipeline-stage == 'dev' }}
      run: |
        npm login --registry=${{ env.JF_URL }}/artifactory/api/npm/clients-npm-dev-local/
        npm publish --registry ${{ env.JF_URL }}/artifactory/api/npm/clients-npm-dev-local/
      working-directory: downloaded-artifacts/aerospike/${{ inputs.new_version }}
      env:
        JF_URL: https://aerospike.jfrog.io

    - name: publish npm package to Jfrog stage repository
      if: ${{ inputs.pipeline-stage == 'stage' }}
      run: |
        npm login --registry=${{ env.JF_URL }}/artifactory/api/npm/clients-npm-stage-local/
        npm publish --registry ${{ env.JF_URL }}/artifactory/api/npm/clients-npm-stage-local/
      working-directory: downloaded-artifacts/aerospike/${{ inputs.new_version }}
      env:
        JF_URL: https://aerospike.jfrog.io

    - name: publish npm package to Jfrog prod repository
      if: ${{ inputs.pipeline-stage == 'master' }}
      run: |
        npm login --registry=${{ env.JF_URL }}/artifactory/api/npm/clients-npm-prod-public-local/
        npm publish --registry ${{ env.JF_URL }}/artifactory/api/npm/clients-npm-prod-public-local/
      working-directory: downloaded-artifacts/aerospike/${{ inputs.new_version }}
      env:
        JF_URL: https://aerospike.jfrog.io
