name: 'Comprehensive tests'
run-name: 'Comprehensive tests (nodejs-tags=${{ inputs.nodejs-tags }}, platform-tag=${{ inputs.platform-tag }}, run_tests=${{ inputs.run_tests }}, use-server-rc=${{ inputs.use-server-rc }}, server-tag=${{ inputs.server-tag }})'

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  statuses: write
  contents: read

on:

  workflow_call:
    inputs:
      nodejs-tags:
        type: string
        required: false
        default: '[["v115", "20"], ["v127", "22"], ["v137", "24"], ["v141", "25"]]'
      platform-tag:
        type: string
        required: true  
      version:
        type: string
        description: Build version
        required: true
      run_tests:
        type: boolean
        required: false
        default: true
      server-tag:
        required: false
        type: string
        default: '8.1.1.0'
        description: 'Server docker image tag'
    secrets:
      soup_hat:
        required: true
      cell_girl:
        required: true
      song_loss:
        required: true

env:
  COMMIT_SHA_TO_BUILD_AND_TEST: ${{ github.sha }}

jobs:
  get-runner-os:
    outputs:
      runner-os: ${{ steps.get-runner-os.outputs.runner_os }}
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - id: get-runner-os
      run: |
        declare -A map
        map[manylinux_x86_64]="ubuntu-22.04"
        map[manylinux_aarch64]="ubuntu-22.04-arm"
        map[win_amd64]="windows-2022"
        map[macosx_x86_64]="macos-14-large"
        map[macosx_x86_64_2]="macos-15-large"
        map[macosx_arm64]="SMA2"
        map[macosx_arm64_2]="SMA3"
        echo runner_os=${map[${{ inputs.platform-tag }}]} >> $GITHUB_OUTPUT
      shell: bash


  test-ee:
    needs: get-runner-os
    if: ${{ inputs.run_tests && (inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'macosx_x86_64') }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with: 
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}

    - name: Remove aerospike docker image
      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
      run: |
        if docker ps -aq | grep -q .; then
          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
        else
          echo "No containers to remove."
        fi

    # TODO: combine this composite action and the above into one
    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        # npm install *.tgz --no-save
        tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
        # macOS x86 doesn't have tree by default
        # tree .
      shell: "bash -ex {0}"

    - name: Install test dependencies
      if: ${{ inputs.run_tests && (startsWith(inputs.platform-tag, 'manylinux') || inputs.platform-tag == 'macosx_arm64') }}
      run: npm ci --ignore-scripts

    - name: Run tests
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux')}}
      run: |
        cat .mocharc.yml
        OPTIONS="-t 40000 -h 127.0.0.1 --port 3000 -U superuser -P superuser" npm run test

    - if: ${{ always() }}
      run: docker logs aerospike

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-pnpm:
    needs: get-runner-os
    if: ${{ inputs.run_tests && (inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'macosx_x86_64') }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with: 
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}

    - name: Remove aerospike docker image
      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
      run: |
        if docker ps -aq | grep -q .; then
          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
        else
          echo "No containers to remove."
        fi

    # TODO: combine this composite action and the above into one
    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}


    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        # tree .
      shell: "bash -ex {0}"

    - name: Run tests
      if: ${{ inputs.run_tests && (startsWith(inputs.platform-tag, 'manylinux') || inputs.platform-tag == 'macosx_arm64') }}
      run: |
        npm ci --ignore-scripts;
        npm install -g pnpm@9.15.9 --ignore-scripts;
        pnpm --version
        mkdir pnpm
        cp ./scripts/basic_test.js pnpm/basic_test.js
        mv *.tgz pnpm
        cd pnpm
        echo '{}' > package.json
        pnpm add ./*.tgz
        node basic_test.js

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-bun:
    needs: get-runner-os
    if: ${{ inputs.run_tests && (inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'macosx_x86_64') }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with: 
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}

    - name: Remove aerospike docker image
      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
      run: |
        if docker ps -aq | grep -q .; then
          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
        else
          echo "No containers to remove."
        fi

    # TODO: combine this composite action and the above into one
    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}


    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        # tree .
      shell: "bash -ex {0}"

    - name: Run tests
      run: |
        npm ci --ignore-scripts;
        curl -fsSL https://bun.sh/install | bash;
        export PATH="$HOME/.bun/bin:$PATH";
        bun --version;
        mkdir bun;
        cp ./scripts/basic_test.js bun/basic_test.js;
        mv *.tgz bun/
        cd bun;
        echo '{}' > package.json;
        bun add *.tgz
        node basic_test.js;

    #- name: Debug server
    #  run: |
    #    docker ps;
    #    docker logs aerospike;


    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-yarn:
    needs: get-runner-os
    if: ${{ inputs.run_tests && (inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'macosx_x86_64') }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with: 
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}

    - name: Remove aerospike docker image
      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
      run: |
        if docker ps -aq | grep -q .; then
          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
        else
          echo "No containers to remove."
        fi

    # TODO: combine this composite action and the above into one
    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}


    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        # tree .
      shell: "bash -ex {0}"

    - name: Run tests
      if: ${{ inputs.run_tests && (startsWith(inputs.platform-tag, 'manylinux') || inputs.platform-tag == 'macosx_arm64' )}}
      run: |
        npm ci --ignore-scripts
        npm install -g yarn
        yarn --version
        mkdir yarn
        cp ./scripts/basic_test.js yarn/basic_test.js
        mv *.tgz yarn/
        cd yarn
        echo '{}' > package.json
        yarn add file:./aerospike-${{ inputs.version }}.tgz
        node basic_test.js

    #- name: Debug server
    #  run: |
    #    docker ps;
    #    docker logs aerospike;


    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  tests:
    needs: get-runner-os
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
        description:
          - valgrind
          - set-xdr-filter
      fail-fast: false
    if: ${{ inputs.platform-tag == 'manylinux_x86_64' }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    # REUSABLE PART
    # - name: Create status check message
    #   run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
    #   shell: bash

    # TODO: we need to create unique commit messages for each matrix item
    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        # We need the last tag before the ref, so we can relabel the version if needed
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}

    - name: Remove aerospike docker image
      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
      run: |
        if docker ps -aq | grep -q .; then
          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
        else
          echo "No containers to remove."
        fi

    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' }}
      uses: ./.github/actions/run-ee-server-for-ext-container
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ secrets.soup_hat }}
        docker-hub-password: ${{ secrets.cell_girl }}

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
        JF_PROJECT: "database"
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
        # tree .
      shell: "bash -ex {0}"

    - name: Install test dependencies
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: |
        npm ci --ignore-scripts
        # tree ./node_modules
        # tree ../node_modules

    - name: Install Aerolab
      if: ${{ matrix.description == 'set-xdr-filter' }}
      run: |
        curl -L -o aerolab.zip https://github.com/aerospike/aerolab/releases/download/7.8.0/aerolab-linux-amd64-7.8.0.zip
        unzip aerolab.zip
        chmod +x aerolab
        sudo mv aerolab /usr/local/bin/
        aerolab version
        aerolab config backend -t docker
        aerolab xdr create-clusters -n dc1 -c 3 -N dc2 -C 3 -M test
        aerolab cluster list
        npm run test --testfile=set_xdr_filter.js -- --testXDR true --h 172.17.0.2 --port 3100;
        # Cleanup steps
        echo y | aerolab cluster destroy --name dc1
        echo y | aerolab cluster destroy --name dc2

    - name: install valgrind and run tests
      if: ${{ matrix.description == 'valgrind' }}
      run: |
        sudo apt-get update;
        sudo apt-get install -y valgrind;
        MOCHA_OPTIONS="--timeout 40000" OPTIONS="-t 40000 -h 127.0.0.1 --port 3000 -U superuser -P superuser" npm run valgrind;

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-tsc-compile:
    needs: get-runner-os
    if: ${{ inputs.run_tests }}
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    # REUSABLE PART
    # - name: Create status check message
    #   run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
    #   shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        # We need the last tag before the ref, so we can relabel the version if needed
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}


    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
        # tree .
      shell: "bash -ex {0}"

    - name: Install test dependencies
      if: ${{ inputs.run_tests }}
      run: |
        npm ci --ignore-scripts;

    - name: Run tests
      run: npx tsc; 

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-metrics:
    needs: get-runner-os
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    if: ${{ inputs.run_tests && (inputs['platform-tag'] != 'macosx_x86_64' && inputs['platform-tag'] != 'win_amd64' && inputs['platform-tag']  != 'macosx_arm64' ) }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    # REUSABLE PART
    # - name: Create status check message
    #   run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
    #   shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        # We need the last tag before the ref, so we can relabel the version if needed
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
        # tree .
      shell: "bash -ex {0}"

    - name: Install test dependencies
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: |
        npm ci --ignore-scripts;

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - name: Run tests
      if: ${{ inputs.run_tests && (startsWith(inputs.platform-tag, 'manylinux') || inputs.platform-tag == 'macosx_x86_64') }}
      run: |
        docker pull aerospike/aerospike-server:latest;
        npm run test --testfile=metrics_node_close.js -- --testMetrics true --h localhost --port 3000  --t 50000;
        npm run test --testfile=metrics_cluster_name.js -- --testMetrics true --h localhost --port 3000  --t 50000;

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-ce:
    needs: get-runner-os
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    if: ${{ inputs.run_tests && (inputs.platform-tag != 'win_amd64' && inputs.platform-tag != 'macosx_x86_64') }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    # REUSABLE PART
    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="test-ce (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        # We need the last tag before the ref, so we can relabel the version if needed
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: Run latest Community edition Aerospike server
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: docker run --ulimit nofile=15000:15000 -d --name aerospike -e DEFAULT_TTL=2592000 -p 3000-3002:3000-3002 aerospike/aerospike-server:8.1.1.0

    - uses: ./.github/actions/wait-for-as-server-to-start
      with:
        container-name: aerospike

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
        # tree .
      shell: "bash -ex {0}"

    - name: Install test dependencies
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: |
        npm ci --ignore-scripts;

    - name: Run tests
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: npm run test -- --h localhost --port 3000;

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-timeout-delay:
    needs: get-runner-os
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    if: ${{ inputs.run_tests && (inputs.platform-tag != 'win_amd64' && inputs.platform-tag != 'macosx_x86_64' && inputs.platform-tag != 'macosx_arm64' ) }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    # REUSABLE PART
    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="test-ce (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        # We need the last tag before the ref, so we can relabel the version if needed
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: Run latest Community edition Aerospike server
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: docker run --ulimit nofile=15000:15000 -d --name aerospike -e DEFAULT_TTL=2592000 -p 3000-3002:3000-3002 aerospike/aerospike-server:8.1.1.0

    - name: Add 10ms latency to Docker traffic
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: |
        sudo tc qdisc add dev lo root netem delay 10ms

    - uses: ./.github/actions/wait-for-as-server-to-start
      with:
        container-name: aerospike

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
        # tree .
      shell: "bash -ex {0}"

    - name: Install test dependencies
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: |
        npm ci --ignore-scripts;
        # tree ./node_modules
        # tree ../node_modules

    - name: Run tests
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: |
        npm run test --testfile=timeout_delay.js -- --testTimeoutDelay true --h localhost --port 3000;
        sudo tc qdisc del dev lo root netem

    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-tsc-compile-self-hosted:
    needs: get-runner-os
    strategy:
      fail-fast: false
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    if: ${{ inputs.run_tests && (inputs['platform-tag'] != 'macosx_x86_64' && inputs['platform-tag'] != 'win_amd64' && inputs['platform-tag'] != 'macosx_arm64' ) }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      # REUSABLE SECTION
      - name: Create status check message
        run: echo STATUS_CHECK_MESSAGE="Test on self hosted (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
        shell: bash

      # - name: Show job status for commit
      #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
      #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
      #   with:
      #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
      #     context: ${{ env.STATUS_CHECK_MESSAGE }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Need to be able to save Docker Hub credentials to keychain
      - if: ${{ inputs.platform-tag == 'macosx_arm64' }}
        run: security unlock-keychain -p ${{ secrets.song_loss }}

      - name: Set up JFrog credentials
        uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
        env:
          JF_URL: https://aerospike.jfrog.io
        with:
          oidc-provider-name: database-gh-aerospike
          oidc-audience: database-gh-aerospike

      - run: |
          jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
          tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
          # tree .
        shell: "bash -ex {0}"

      - name: Install test dependencies
        if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
        run: |
          npm ci --ignore-scripts;
          # tree ./node_modules
          # tree ../node_modules
  
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        #if: ${{ inputs.platform-tag == 'macosx_arm64' }}
        with:
          node-version: ${{ matrix.nodejs-tag[1] }}

      # REUSABLE SECTION 

      - name: Run tests
        if: ${{ inputs.platform-tag == 'win_amd64' }}
        run: |
          npx tsc;

      # - name: Show job status for commit
      #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
      #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
      #   with:
      #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
      #     status: ${{ job.status }}
      #     context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-user-agent-ce:
    needs: get-runner-os
    strategy:
      matrix:
        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
      fail-fast: false
    if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    # REUSABLE PART
    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="test-ce (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    # - name: Show job status for commit
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        # We need the last tag before the ref, so we can relabel the version if needed
        fetch-depth: 0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.nodejs-tag[1] }}

    - name: Run latest Community edition Aerospike server
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: docker run --ulimit nofile=15000:15000 -d --name aerospike -e DEFAULT_TTL=2592000 -p 3000-3002:3000-3002 aerospike/aerospike-server:8.1.1.0

    - uses: ./.github/actions/wait-for-as-server-to-start
      with:
        container-name: aerospike

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: database-gh-aerospike
        oidc-audience: database-gh-aerospike

    - run: |
        jf rt dl --flat --fail-no-op "database-npm-dev-local/aerospike/-/aerospike-${{ inputs.version }}.tgz" .
        tar xvf aerospike-${{ inputs.version }}.tgz --strip-components 1 'package/lib/binding'
        # tree .
      shell: "bash -ex {0}"

    - name: Install test dependencies
      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
      run: |
        npm ci --ignore-scripts;
        # tree ./node_modules
        # tree ../node_modules

      # Even for server versions < 8.1 that don't support user agent, this client version should still work on older servers
    - name: Run client in background
      run: |
        cat <<'EOF' > test/run-client-in-bg.js
        const Aerospike = require('../lib/aerospike.js');

        const main = async () => {
          let client;
          try {
            client = await Aerospike.connect({ hosts: '127.0.0.1:3000', appId: '1234567' });
            while (true) {
              await new Promise(r => setTimeout(r, 1000));
            }
          } catch (e) {
            console.error(e);
            process.exit(1);
          } finally {
            client && client.close();
          }



        };

        main();
        EOF

        # This shell will be closed once this step completes
        nohup node test/run-client-in-bg.js &
        # TODO: We want to check if the python script raises a syntax error or not. (should fail immediately)
        # When background processes fail, this step won't fail.

    - name: Confirm that the user agent shows the correct client language and version (only for server 8.1)
      run: |
        set -e
        set -x
        server_version=$(docker exec ${{ env.CONTAINER_NAME }} asinfo -v build)
        major_num=$(echo $server_version | cut -d '.' -f 1)
        minor_num=$(echo $server_version | cut -d '.' -f 2)
        if [[ $major_num -lt 8 || ( $major_num -eq 8 && $minor_num -lt 1 ) ]]; then
          exit 0
        fi
        info_cmd_response=$(docker exec ${{ env.CONTAINER_NAME }} asinfo -v "user-agents" | head -n 1)
        echo "Info command response: $info_cmd_response"
        # Response format: user-agent=<base64 encoded string>:...
        user_agent_base64_encoded=$(echo $info_cmd_response | perl -n -E 'say $1 if m/user-agent= ([a-zA-Z0-9+\/=]+) :/x')
        echo $user_agent_base64_encoded
        user_agent=$(echo $user_agent_base64_encoded | base64 -d)
        echo $user_agent
        # TODO: combine into one regex
        # User agent format: <format-version>,<client language>-<version>,...
        client_language=$(echo $user_agent | perl -n -E 'say $1 if m/[0-9]+, ([a-z]+) -/x')
        client_version=$(echo $user_agent | perl -n -E 'say $1 if m/[0-9]+,[a-z]+- ([0-9.a-zA-Z+]+),/x')
        client_app_id=$(echo $user_agent | perl -n -E 'say $1 if m/,[^,]+,([^,]+)/')
        client_version="${client_version//$'\n'/}"
        echo $client_language
        echo "nodejs"
        test "$client_language" = "nodejs"
        echo $client_version
        echo $expected_client_version
        expected_client_version=$(node -p "require('./package.json').version.split('-')[0]")
        test "$client_version" = "$expected_client_version"
        echo $client_app_id
        echo "1234567"
        test "$client_app_id" = "1234567"
      shell: bash
      env:
        CONTAINER_NAME: aerospike


    # - name: Set final commit status
    #   uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
    #   if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
    #   with:
    #     sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
    #     status: ${{ job.status }}
    #     context: ${{ env.STATUS_CHECK_MESSAGE }}
