name: Stage Tests
run-name: Stage tests (run_tests=${{ inputs.run_tests }}, use-server-rc=${{ inputs.use-server-rc }}, server-tag=${{ inputs.server-tag }})

on:
  workflow_dispatch:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: false
      version:
        type: string
        description: Build version
        required: true
      server-tag:
        type: string
        required: false
        default: '8.1.1.0'
  workflow_call:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: false
      version:
        type: string
        description: Build version
        required: true
      server-tag:
        type: string
        required: false
        default: '8.1.2.0'
    secrets:
      soup_hat:
        required: true
      cell_girl:
        required: true
      song_loss:
        required: true

jobs:
  comprehensive-tests:
    strategy:
      matrix:
        platform-tag: [
          "linux_x86_64",
          "linux_aarch64",
          "darwin_x86_64",
          #"darwin_x86_64_2",
          "darwin_arm64",
          #"darwin_arm64_2",
          "win32_x64"
        ]
      fail-fast: false
    uses: ./.github/workflows/stage-comprehensive-tests.yml
    with:
      platform-tag: ${{ matrix.platform-tag }}
      run_tests: ${{ inputs.run_tests }}
      server-tag: ${{ inputs.server-tag }}
      version: ${{ inputs.version }}
    secrets:
      soup_hat: ${{ secrets.soup_hat }}
      cell_girl: ${{ secrets.cell_girl }}
      song_loss: ${{ secrets.song_loss }}