name: Bump version

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    outputs:
      dev_version:
        value: ${{ jobs.stage-get-jfrog-version.outputs.dev_version }}
      tag_version:
        value: ${{ jobs.stage-get-jfrog-version.outputs.tag_version }}

jobs:
  stage-get-jfrog-version:
    name: Get most recent JFrog version string
    runs-on: ubuntu-22.04
    outputs:
      dev_version: ${{ steps.stage-get-jfrog-version.outputs.dev_version }}
      tag_version: ${{ steps.stage-get-jfrog-version.outputs.tag_version }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - id: stage-get-jfrog-version
      run: |
        echo dev_version=$(npm pkg get version | tr -d '"') >> $GITHUB_OUTPUT
        echo tag_version=$(git tag -l --sort=-creatordate | head -n 1) >> $GITHUB_OUTPUT
