name: Bump version

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    outputs:
      dev_version:
        value: ${{ jobs.stage-get-jfrog-version.outputs.dev_version }}
      bump_sha:
        value: ${{ jobs.update-version-in-repo.outputs.bump_sha }}

jobs:
  stage-get-jfrog-version:
    name: Get most recent JFrog version string
    runs-on: ubuntu-22.04
    outputs:
      dev_version: ${{ steps.stage-get-jfrog-version.outputs.dev_version }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Get jfrog version
      id: stage-get-jfrog-version
      run: |
        echo "dev_version=$(jfrog rt s "clients-npm-dev-local/aerospike/*" | jq -r '.[]?.path | capture("aerospike/(?<version>[^/]+)") | .version' | grep -v '^-$' | grep -v '^lib$' | sort -V | grep -v 'rc' | tail -n1)" >> $GITHUB_OUTPUT

    - name: Print jfrog version
      run: echo "Jfrog version is ${{ steps.stage-get-jfrog-version.outputs.dev_version }}"
