name: Bump version

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    secrets:
      desk_mood:
        required: true
    outputs:
      dev_version:
        value: ${{ jobs.stage-get-jfrog-version.outputs.dev_version }}
      bump_sha:
        value: ${{ jobs.update-version-in-repo.outputs.bump_sha }}

jobs:
  stage-get-jfrog-version:
    name: Get most recent JFrog version string
    runs-on: ubuntu-22.04
    outputs:
      dev_version: ${{ steps.stage-get-jfrog-version.outputs.dev_version }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        token: ${{ secrets.desk_mood }}

    - name: Set up JFrog credentials
      uses: jfrog/setup-jfrog-cli@5b06f730cc5a6f55d78b30753f8583454b08c0aa # v4.8.1
      env:
        JF_URL: https://aerospike.jfrog.io
      with:
        oidc-provider-name: gh-aerospike-clients
        oidc-audience: aerospike/clients

    - name: Get jfrog version
      id: stage-get-jfrog-version
      run: |
        echo "dev_version=$(jfrog rt s "clients-npm-dev-local/aerospike/*" | jq -r '.[]?.path | capture("aerospike/(?<version>[^/]+)") | .version' | grep -v '^-$' | grep -v '^lib$' | sort -V | grep -v 'rc' | tail -n1)" >> $GITHUB_OUTPUT

    - name: Print jfrog version
      run: echo "Jfrog version is ${{ steps.stage-get-jfrog-version.outputs.dev_version }}"
